### PR TITLE
Switch overlay encryption to use IPSec subsystem keys

### PR DESCRIPTION
**Pull request by sanimej**
This has a dependency on [swarmkit #1065](https://github.com/docker/swarmkit/pull/1065)

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by mavenugo** [comment]
@sanimej is this PR dependent on the swarmkit changes ? Though there is not compile time dependencies, It might impact the runtime behaviour. Should we wait for swarmkit to be vendored in before getting this patch into libnetwork for RC3 ?

**Comment by sanimej** [comment]
@mavenugo Yes, this has a runtime dependency on the swarmkit PR I referred to. Without that overlay encryption will fail because we won't get the IPsec keys from the manager.

**Comment by aboch** [comment]
Tested via docker with latest libnetwork and swarmkit.

**Pull request merged**
