### PR TITLE
External key handling via reexec

### PR DESCRIPTION
**Pull request by mavenugo**
+ godep updates on the updated dependancies

### CODE REVIEW

**Comment by mavenugo** [comment]
@mrjana @aboch fixed the CI issue. PTAL.

**Comment by mavenugo** [comment]
@mrjana updated the changes with your suggestion. CI still passes, which is good :). PTAL

**Comment by mrjana** [comment]
@mavenugo Can we not change all godeps to just introduce runc in godeps? github bails out from showing diffs in the `Files Chaged` tab because of too many changes and that prevents me from providing my comments in that tab (only when I provide my comments there it stays there with the PR). Why don't we just update godeps for runc alone by doing the following:
```
godep save github.com/opencontainers/runc
```
This should work and I have done it many times

**Comment by mavenugo** [comment]
@mrjana as discussed, we have some challenges with the `godep save` & we can handle with that cleanly at a later point.
@aboch thanks for the comments. fixed them. Though i dont have to change the buf len to 1024 in return, I still made the changes to be consistent.

**Comment by aboch** [comment]
LGTM

**Comment by mavenugo** [comment]
@mrjana thanks for all the good comments. Its a shame that they are not showing up in github :( 
took care of them all. PTAL.

**Comment by mrjana** [comment]
@mavenugo Thanks for taking care of the comments. LGTM

**Pull request merged**
