### PR TITLE
Delete stale HNS endpoints when creating a network

### PR DESCRIPTION
**Pull request by johnstep**
Signed-off-by: John Stephens <johnstep@docker.com>

When Windows Server 2016 is restarted with the Docker service running, it is possible for endpoints to be deleted from the libnetwork store without being deleted from HNS. This does not occur if the Docker service is stopped cleanly first, or forcibly terminated (since the endpoints still exist in both). This change works around the issue by removing any stale HNS endpoints for a network when creating it.

@pradipd @msabansal

### CODE REVIEW

**Comment by fcrisciani** [comment]
@johnstep maybe the comment at https://github.com/docker/libnetwork/pull/2098/files#diff-62a5665cda9650d2d6f6a7600c584b33R297 should be updated too.

**Comment by pradipd** [comment]
FYI @dineshgovindasamy

**Comment by pradipd** [comment]
From what I understand about the problem this LGTM.
I will have @msabansal review when he is back.

**Comment by ddebroy** [comment]
If the API to create networks (exposed by the daemon) is invoked multiple times with the same network, is it possible that with this change, there may now be undesired consequences (i.e. deletion of endpoints)?

Is there any way to move the check-and-clean-up logic to driver init rather than network creation?

**Comment by pradipd** [comment]
Wouldn't the check at L270 prevent that?

**Comment by ddebroy** [comment]
Indeed. Thanks for pointing that out, Pradip.

**Comment by dineshgovindasamy** [comment]
LGTM

**Comment by fcrisciani** [comment]
ok, merging it and the test steps can be added as a comment here on the PR

**Comment by ekitagawa** [comment]
Sorry for the delay.   Here are steps for testing.
 
*Please keep in mind that this is really hard to reproduce.  So far, I have been able to reproduce it with Docker for Azure template consistently but no other.  Another cluster with the same version of engine and UCP on Azure will not reproduce.  On AWS side, it happens randomly after leaving the worker node for days or weeks.  Let me know if you want to use my cluster.
 
  1. Join Windows worker node.
  2. check the Windows kernel version with this.
       `$(Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion' BuildLabEx).BuildLabEx`
        *builds older than Jan 2018 are more prone to this issue.*
  3. restart Windows node
  4. check if you see any of the following symptoms:
      * Windows worker node gets kicked out of swarm (but Windows node itself shows `swarm:pending`)
      * Windows event log shows `fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Unspecified error`
      * UCP agent generates Error while checking for available ports: `Error while checking for available ports: The following required ports are already in use on your host - 12376.` 
  5. Clean up the node using the steps here:
      https://success.docker.com/article/windows-node-becomes-unavailable-after-restart
  6. Apply the patched.
  7. re-join the node to UCP.
  8. `Restart-Computer`
  9. Make sure the windows nodes is green.

**Comment by ekitagawa** [comment]
@johnstep I tested `17.06.2-ee-8-tp1` but it doesn't work.  In fact, I tested your cherry picked TP again, and it doesn't work either.  Whenever I restart, node gets kicked out of swarm, and it shows up as `Swarm: Pending`.  Maybe, we are looking at different issue?

**Comment by ekitagawa** [comment]
If I do the cleanup with `Remove-ContainerNetwork` and rejoin, it works fine...

**Pull request merged**
