### PR TITLE
Add the ability to request a specific IP address when creating a new endpoint

### PR DESCRIPTION
**Pull request by boucher**
When restoring a container, we want to request the same IP address we had before. I'm not sure if this is really the best way to do that, so I'm open to changing this if there are any alternate proposals.

### CODE REVIEW

**Comment by mavenugo** [comment]
@boucher Thanks for the patch. Please refer to https://github.com/docker/libnetwork/issues/161 and your approach handles one part of the fix. https://github.com/docker/libnetwork/pull/199 solves one other part. I will be fixing the docker side of the fix today.

Please fix the build error. And please also always write a test-case for any code change.

**Comment by boucher** [comment]
Thanks for the quick feedback. Does FromMap in #199 make this unnecessary? If so I'm happy to close it, otherwise I'll look into adding a test case.

**Comment by boucher** [comment]
Fixed the build issue and added a test case.

**Comment by mavenugo** [comment]
@boucher this is still useful and we can make use of it as one of the blocks of the bigger puzzle. thanks for the contribution. will review this shortly.

**Comment by boucher** [comment]
@mavenugo Have you had a chance to take a look?

**Comment by mavenugo** [comment]
@boucher today I will. stay tuned.

**Comment by boucher** [comment]
I'm not sure I follow, but if I understand what you're saying, you're suggesting that the people setting the option would set it as a string? I'm not sure why that's the case, since the other options don't seem to be set as strings (e.g. MacAddress), and I'm not setting it as a string in my upstream use in Docker.

**Comment by mavenugo** [comment]
@boucher that's because, MacAddress is a well-known option in `docker run` & hence it is formatted programmatically before sending it to libnetwork. Whereas, we are not adding `--ip` flag in `docker run` for this use-case, but trying to use the user label mechanism to pass the info transparently. PTAL : https://github.com/docker/docker/pull/13476
If we have to introduce a `--ip` flag in `docker run`, then we could format it as well. But we are trying to avoid adding special driver specific flags in docker to control the flag sprawl, by the use of labels.

Having said that, there is some concern to the general approach of using the labels as seen in the above PR.

**Comment by boucher** [comment]
Fair enough. It still seems like you'd want docker to be responsible for the label -> ip translation/parsing, so that it could better define the behavior of what should happen given an invalid IP address.

**Comment by boucher** [comment]
Just to clarify my earlier comment about how I'm using this in Docker: when you restore a container, criu will try to set its ip address to whatever it was when it was checkpointed, so we want to request that specific IP when we restore. The information is stored/retrieved straight from the container's state, so it's already parsed. Exposing this feature to users is definitely cool, but not actually why I need this.

**Comment by boucher** [comment]
All that being said, the change is obviously pretty simple so I'm happy to update the PR.

**Comment by mavenugo** [comment]
@boucher hate to say this, but can you please hold on with the changes ?
We have to make sure that we address the comments from https://github.com/docker/docker/pull/13476 before we could make this change.

**Comment by boucher** [comment]
@mavenugo Any updates on the various other pending issues here?

**Comment by mavenugo** [comment]
@boucher PTAL https://github.com/docker/libnetwork/issues/161 and https://github.com/docker/docker/pull/13476. Based on all the discussions and gathering opinions, using the label approach to assigning IP is not the preferred method. Docker maintainers prefers a more abstract way to separate user intent from operational intent.
Based on this feedback and various other discussions on a flexible ip address management, we feel that having a pluggable IPAM will help a great deal. Please share your opinion.
If you agree, we can close this PR and work together on the pluggable IPAM solution.

**Comment by aboch** [comment]
Things have changed since this PR was opened: With the introduction of the IPAM entity in libnetwork, container IP addresses are managed by the IPAM driver or explicitly chosen by user and passed via IPAM specific EndpoinOption to libnetwork.

Therefore I am closing this PR as it passes the user specified address in a way which no longer fits in libnetwork model.

**Comment by xusxlinux** [comment]
1

**Pull request closed without merging**
