### PR TITLE
Use ioctl to create bridge

### PR DESCRIPTION
**Pull request by mrjana**
Please see commit notes for more information

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM. Works on my CentOS 6.6.

**Comment by mavenugo** [comment]
Fixes https://github.com/docker/docker/issues/14174

**Comment by mavenugo** [comment]
Fixes https://github.com/docker/docker/issues/14024

**Comment by visualphoenix** [comment]
@mavenugo I imagine it also fixes #312 then. Once 1.7.1 is released and I can verify #312 is fixed I can close it and docker/docker#14024

**Comment by mavenugo** [comment]
@visualphoenix Yes it fixes #312 as well.

**Pull request merged**
