### PR TITLE
[WIP] DO NOT MERGE YET Revert "[Backport 17.06] Overlay fix for transient IP reuse"

### PR DESCRIPTION
**Pull request by andrewhsu**
Reverts docker/libnetwork#1965

From discussion with @fcrisciani, needs more work. Better to revert for now so we can vndr the `bump_17.06` branch with changes from @abhi.

### CODE REVIEW

**Comment by andrewhsu** [comment]
cc @mavenugo

**Comment by mavenugo** [comment]
@andrewhsu reverting this will affect https://github.com/docker/libnetwork/pull/1969. Are you sure about it ? cc @fcrisciani

**Comment by fcrisciani** [comment]
This fix is taking care of the failure that I was seeing yesterday. https://github.com/docker/libnetwork/pull/1969
Not sure about the timing here, today I did not have time to do any further testing, I'm stuck with Liberty Mutual

**Comment by mavenugo** [comment]
@fcrisciani since https://github.com/docker/libnetwork/pull/1969 is opened against the bump_17.06 branch and it is dependent on https://github.com/docker/libnetwork/pull/1965... reverting https://github.com/docker/libnetwork/pull/1965 will make https://github.com/docker/libnetwork/pull/1969 useless.

So am not sure what is the purpose of this PR, when https://github.com/docker/libnetwork/pull/1969 was opened to address the issue ?
cc @andrewhsu do you know ?

**Comment by andrewhsu** [comment]
this is not needed anymore because we got #1969

**Pull request closed without merging**
