### PR TITLE
Windows: Enable compile

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>
@swernli

This PR is part of the proposal described in docker/docker issue 10662 to port the docker daemon to Windows. This PR enables compilation of libnetwork on Windows with a placeholder driver.

### CODE REVIEW

**Comment by mavenugo** [comment]
@jhowardmsft thanks for the PR & its awesome to see windows support in for libnetwork.
There are couple of things with respect this PR that I would like to understand.

1. What is the proposed functionality that the windows driver would provide. Is this similar to the default `bridge` driver ? If yes, we would very much like to make the default `bridge` driver multi-platform aware and provide consistent features across platforms. That will avoid the need to have platform specific default drivers such as `drivers/windows`.

2. Hoping to see a `sandbox_windows` soon which brings the equivalent sandbox functionality for windows. Is it something we can expect soon & if so, can you share some plans ?

**Comment by jhowardmsft** [comment]
@mavenugo - thanks for reviewing. The answers to your questions remain somewhat open here still. However, hopefully not speaking out of turn for the Windows Networking team.... I actually expect that the network driver on Windows will be vastly different to bridge on Linux in functionality. This is because containers on Windows will leverage the virtual switch (from Hyper-V) to provide (virtual) networking functionality, whereas on Linux it is necessary for docker to configure Linux networking directly. I would expect the Windows driver to be largely passthrough down through the HCS (Host Compute Service management layer) onto the virtual switch. To put some context into what was demo'd at //build with the Windows docker daemon and the network driver (pre-libnetwork) that was in that daemon. It really did do nothing except allocate MAC addresses from a pool based on the IP address of the servers primary NIC. Even that will not be necessary ultimately as the virtual switch will do that on behalf of docker on Windows. We only did it that way simply because it wasn't hooked up through HCS in time for the demos, and further only as a precaution incase multiple folks were demoing on the same subnet and would have potentially caused MAC address collisions. I hope that answers why at this point we feel it better to have an independent windows driver.

**Comment by jhowardmsft** [comment]
PS - What's the right IRC channel for libnetwork discussions? It didn't appear to be either #libnetwork or #docker-libnetwork. Thx :)

**Comment by mavenugo** [comment]
@jhowardmsft its #docker-network :)

**Comment by mrjana** [comment]
@jhowardmsft LGTM

**Comment by mavenugo** [comment]
@jhowardmsft thanks for the confirmation. We were discussing about the best way to handle multi-platform in-built drivers as freebsd has the same issue. Considering the fact that we need to unblock you for building docker daemon in windows platform (same goes to freebsd), this LGTM.

We can have a detailed discussion shortly on the best approach to take that gives a consistent experience to the end-users.

**Comment by jhowardmsft** [comment]
@mrjana @mavenugo Thanks! Should open a separate PR in docker/docker to get this re-vendored into master?

**Comment by icecrime** [comment]
@mavenugo Do you have CI to ensure that the Windows build will be preserved in the long run?

**Comment by mrjana** [comment]
@icecrime we don't. But we should explore what needs to be done. Until then it will be caught by docker/docker CI

**Comment by jhowardmsft** [comment]
Unfortunately there's no Windows daemon build CI on docker/docker at the moment (other PRs required for daemon to build)

**Comment by mrjana** [comment]
@jhowardmsft This along with a bunch of other commits are going to be vendored in shortly

**Comment by mrjana** [comment]
@jhowardmsft I was just saying when that is going to be available :-)

**Comment by jhowardmsft** [comment]
Soon, I hope. Waiting for other PRs to merge, and obviously a revendor on libnetwork

**Comment by mavenugo** [comment]
@jhowardmsft yes. I will be pushing a PR to revendor libnetwork to docker today.

**Comment by jhowardmsft** [comment]
@mavenugo Yay, thanks!

**Comment by mavenugo** [comment]
@jhowardmsft @icecrime @mrjana https://github.com/docker/docker/pull/13682

**Pull request merged**
