### PR TITLE
iptables: jump to DOCKER-USER first

### LINKED ISSUE #1827: DOCKER-INGRESS trumps DOCKER-USER
**Description**

The `DOCKER-INGRESS` chain is inserted above the `DOCKER-USER` chain the first time an ingress mode port is published.

**Steps to reproduce the issue:**
1. Intall Docker 17.06 CE
1. Form a two-node swarm with one manager and one worker
1. Start a service on the worker 

        docker service create --name listen --constraint node.role==worker nginx

1. Add a published port to the service

        docker service update --publish-add 8000:80 listen

**Describe the results you received:**

On the manager node:

    Chain FORWARD (policy DROP 0 packets, 0 bytes)
     pkts bytes target     prot opt in     out     source               destination
        0     0 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0
        0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    ...

**Describe the results you expected:**

On the manager node:

    Chain FORWARD (policy DROP 0 packets, 0 bytes)
     pkts bytes target     prot opt in     out     source               destination
        0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
        0     0 DOCKER-INGRESS  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    ...

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:20:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:21:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
[vagrant@node01 ~]$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: xkg8qatmicxgd3f7svxnquh9l
 Is Manager: true
 ClusterID: 7hh3eimfcqou24um83q7sdl83
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.121.237
 Manager Addresses:
  192.168.121.237:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.21.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 2.288GiB
Name: node01
ID: N6ZC:323C:2ZVX:JP3B:VV7J:V22X:LG6B:M4P7:HRKJ:BSRT:Q6UJ:Y26P
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
CentOS Linux release 7.3.1611 (Core) 
```

### PR DESCRIPTION
**Pull request by wenjianhn**
Fixes #1827

Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>

### CODE REVIEW

**Comment by fcrisciani** [comment]
Will bringing line: https://github.com/docker/libnetwork/blob/master/controller.go#L851 to https://github.com/docker/libnetwork/blob/master/controller.go#L844 have the same result instead of adding another call?

**Comment by wenjianhn** [comment]
@fcrisciani I don't think so.

For this bug, func (c *controller) NewNetwork is not called when DOCKER-INGRESS trumps DOCKER-USER.

**Comment by fcrisciani** [comment]
@wenjianhn if that is the case then we have to make sure that the behavior is the same for both code paths. 
For example this function: https://github.com/docker/libnetwork/pull/1845/files#diff-0b812768b348f54bfada8f60e17dd3acR447 is still going to put the DOCKER-INGRESS as first rule if found

**Comment by wenjianhn** [comment]
@fcrisciani It's already taken care of.

arrangeUserFilterRule() is called right after arrangeIngressFilterRule().
See https://github.com/docker/libnetwork/blob/bump_17.06.0/controller.go#L851

**Comment by fcrisciani** [comment]
@wenjianhn you are right thanks for explaining, looks like there is some cleanup that can be done over this area, just compacting the ingressChain creation with the userChain to avoid the need of calling the reordering, but just do the proper programming all the time.
Anyway this fix is contained enough and address the specific issue, LGTM.

On the side I opened this ticket: https://github.com/docker/libnetwork/issues/1852 to keep in mind a future possible cleanup

**Comment by wenjianhn** [comment]
@fcrisciani Thanks.

I agree that we need to clean the code.
I will have a look at the ticket.

**Comment by fcrisciani** [comment]
@wenjianhn thanks.

@mavenugo @abhinandanpb can you guys review too?

**Comment by sanimej** [comment]
LGTM

**Pull request merged**
