### PR TITLE
boltdb/bolt==>bbolt, revendor Microsoft/*, Windows compilation.

### LINKED ISSUE #1950: Saving endpoint to store fails in windows under concurrent load
We are trying to create a lot of parallel containers on windows. As part of the workflow multiple endpoints are being created and saved simultaneously. When this happens some container creation fails as docker is not able to save the endpoint to store:

time="2017-09-12T19:53:30.792343000-07:00" level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: failed to create endpoint eager_newton on network nat: failed to save endpoint 53944a9 to store: failed to update store for object type *windows.hnsEndpoint: open C:\docker/network/files/local-kv.db.lock: The process cannot access the file cause it is being used by another process." error_type=types.internal module=api 

I am waiting for a repro machine to track this. Probably only happens on slow machines but creating an issue for tracking. This is also causing some noise in docker CI aswell.

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

Almost fixes https://github.com/docker/libnetwork/issues/1950.

Most of this PR is vendoring.

- I've bumped Microsoft/hcsshim and Microsoft/go-winio to the latest versions, which are the same as the ones currently vendored in the moby/moby repo.

- I've removed the unused syndtr/gocapability

- Replaced boltdb/bolt with go.etc.io/bbolt. Specifically because boltdb/bolt is no longer being maintained, and we need this fix https://github.com/etcd-io/bbolt/pull/122 to fix #1950. That was merged in https://github.com/etcd-io/bbolt/releases/tag/v1.3.1-etcd.8.

- I've also made `go build ./…` closer to building on Windows. I should really tackle vishvanada\netns one day as that's the next blocker for that. But not for this PR.

Once all this is merged, we need a follow-on PR to revendor libnetwork into moby/moby to finally fix #1950 (which should really be open in the moby/moby repo, but not important.)

@carlfischer1 FYI

@mavenugo PTAL

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Could someone help me understand what this failure might mean? Or help debug it? I'm not that familiar with libnetwork. Tentatively possible is a regression due to boltdb, purely based on supposition in that it has db in the name of the test.

```
--- FAIL: TestNetworkDBCRUDMediumCluster (16.92s)
	networkdb_test.go:112: Network existence verification failed
	networkdb_test.go:136: Entry existence verification test failed for node3(5e292e4e65e9)
	networkdb_test.go:136: Entry existence verification test failed for node3(5e292e4e65e9)
	networkdb_test.go:455: assertion failed: expression is false: strings.Contains(err.Error(), "deleted and pending garbage collection")
```

**Comment by jhowardmsft** [comment]
I suspect this is a flaky test. It doesn't look like `NetworkDB` uses bolt (bbolt). On a second run, it failed in a different way:

```
=== RUN   TestNetworkDBCRUDMediumCluster
--- FAIL: TestNetworkDBCRUDMediumCluster (2.06s)
	networkdb_test.go:57: Number of nodes for node3 into the cluster does not match 5 != 4
```


I'll give it a third CI attempt...

**Comment by mavenugo** [comment]
Yes. I dont know why and how networkdb fails for boltdb changes.
@fcrisciani might know more details on this.

**Comment by thaJeztah** [comment]
Could you squash these three commits? Looks like they should go together;

- Bump libkv to 458977154600b9f23984d9f4b82e79570b5ae12b
- Remove github.com/boltdb/bolt from vendor.conf 
- Vendor go.etcd.io/bbolt @ v1.3.1-etcd.8

**Comment by selansen** [comment]
LGTM

**Comment by thaJeztah** [comment]
thanks!

**Comment by jhowardmsft** [comment]
Who can merge this? I'd really like to get the fix into moby/moby due to the number of people hitting the issue

**Pull request merged**
