### PR TITLE
Cherry picks for the 1.12.x branch

### PR DESCRIPTION
**Pull request by aboch**

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch can you pls point to all the docker issues that this cherry-pick brings in ?
Since it is cherry-picked for the 1.12.x specific branch, its better to be conservative and pick only those that are critical (such as panic), regressions in previous 1.12.x release, etc...

**Comment by aboch** [comment]
@mavenugo I reduced the cherry-pick list. These are the referenced panic issues
https://github.com/docker/docker/issues/28112
https://github.com/docker/docker/issues/28465
https://github.com/docker/for-mac/issues/849
https://github.com/docker/docker/issues/28606
https://github.com/docker/docker/issues/28630
https://github.com/docker/libnetwork/issues/1572
https://github.com/docker/docker/issues/25184

Also #1570 still needs to be review/merged and picked in here, which will solve
https://github.com/docker/docker/issues/28697

**Comment by sanimej** [comment]
#1573 fixes a panic that was seen by a user. But I don't think we have an issue in docker for that.

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
