### PR TITLE
Revert "Enable ping for service vip address"

### PR DESCRIPTION
**Pull request by mavenugo**
This PR reverts https://github.com/docker/libnetwork/pull/1501 because it causes https://github.com/docker/docker/issues/28358.

Also drop icmp-echo-request to bring in consistent Service ping failure behavior.

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @sanimej @aboch

**Comment by mavenugo** [comment]
@sanimej @aboch am also working on the other option that will reply to VIP ping. I will keep you posted shortly.

**Comment by sanimej** [comment]
@mavenugo If you are still working on changes can you add WIP to the title ? I would rather not spend time on reviewing changes that may not be in the final version.

**Comment by mavenugo** [comment]
https://github.com/docker/libnetwork/issues/1566 replaces this PR

**Pull request closed without merging**
