### PR TITLE
Overlay driver support for Solaris

### PR DESCRIPTION
**Pull request by puneetpruthi**
This PR is targetting to add overlay network driver support for Solaris.
The code changes for this PR are stable and open to review. The PR has been tested on Linux as well.

To Dos:
- [x]  Integration testing with docker-engine on Solaris

Signed-off-by: Puneet Pruthi puneetpruthi@gmail.com

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @docker/core-libnetwork-maintainers

**Comment by mavenugo** [comment]
I was discussing with @puneetpruthi about the need for CI and he is working on that.

am currently stuck with windows-overlay support. It would be good if @aboch @sanimej or @mrjana can spend some time reviewing the PR.

**Comment by aboch** [comment]
Most of the code is copied over from the linux implementation, then changed to be a no op.
As for the bridge driver implementation for solaris, I think it is ok for the code to go in so that it can provide the basic functionality and be a base for future improvements to be added.

I look forward for a code cleanup in both bridge and overlay solaris drivers though.

Also there is no CI to test this. I guess you guys will take care of it in docker/docker sometime.


LGTM

**Comment by puneetpruthi** [comment]
Thanks @aboch !
Bridge and Overlay cleanup shall be filed as a followup PR.
About the CI - we are working towards getting that out ASAP.

**Comment by puneetpruthi** [comment]
Thanks @aboch !

**Pull request merged**
