### PR TITLE
Delete endpoint from network map for macvlan driver upon endpoint deletion

### PR DESCRIPTION
**Pull request by sainath14**
Endpoint delete from network map in macvlan driver.

Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>

### CODE REVIEW

**Comment by sainath14** [comment]
ping @mavenugo  PTAL

**Comment by aboch** [comment]
LGTM

**Comment by aboch** [comment]
Can you please pass the proper parameter, the endpoint id.

**Comment by nerdalert** [comment]
Hi@sainath14 if you wouldn't mind changing the patch to `n.deleteEndpoint(ep.id)` as the method is looking for a string. Thanks!

**Comment by sainath14** [comment]
sorry, missed it... please check now

**Comment by nerdalert** [comment]
Thanks, LGTM

**Comment by sainath14** [comment]
I am seeing a rebase conflict. d.storeDelete(ep) is being added an upstream change. Adding deleteEndpoing after the storeDelete sounds correct to me.

**Comment by nerdalert** [comment]
If its from PR #1196 don't worry about that. That is blocked until v1.13. That what you were referring to?

**Comment by sainath14** [comment]
It was from PR #1244

**Comment by aboch** [comment]
LGTM

**Pull request merged**
