### PR TITLE
Overlay networking support for windows

### PR DESCRIPTION
**Pull request by msabansal**
This PR adds support for overlay networking in windows. As part of this PR we have added basic functionality to enable Windows overlay networking in swarm mode and enable service discovery for swarm services. 

There are some open issues for complete swarm support such as:

- Default gateway not being added to containers (for internet access) which we will continue working on. 
- Services only support endpoints in DNSRR mode (--endpoint-mode option)

Signed-off-by: Madhu Venugopal <madhu@docker.com>
Signed-off-by: msabansal <sabansal@microsoft.com>
Signed-off-by: nwoodmsft <Nicholas.Wood@microsoft.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks @msabansal. Since we don't have CI for windows platform, it would be great if you can add the test-results for the windows CI with this changes to make sure these changes doesnt break any existing drivers (NAT, Transparent and others).

Also,  Since Multi-host networking works in swarm-mode along with Service Discovery, I think it would be great if you can attach logs from manual testing results of overlay networking in windows platform which we can use as a reference point for further development.

**Comment by mavenugo** [comment]
@msabansal the CI failures are genuine build issues -

```
# github.com/docker/libnetwork
./agent.go:395: c.addServiceBinding undefined (type *controller has no field or method addServiceBinding)
./agent.go:443: c.rmServiceBinding undefined (type *controller has no field or method rmServiceBinding)
./agent.go:615: c.addServiceBinding undefined (type *controller has no field or method addServiceBinding)
./agent.go:627: c.rmServiceBinding undefined (type *controller has no field or method rmServiceBinding)
./controller.go:329: c.cleanupServiceBindings undefined (type *controller has no field or method cleanupServiceBindings)
./network.go:795: c.cleanupServiceBindings undefined (type *controller has no field or method cleanupServiceBindings)
godep: go exit status 2
make: *** [build-local] Error 1
```

Could you pls fix these ?

**Comment by mavenugo** [comment]
ping @msabansal 

> Since we don't have CI for windows platform, it would be great if you can add the test-results for the windows CI with this changes to make sure these changes doesnt break any existing drivers (NAT, Transparent and others).

> Also, Since Multi-host networking works in swarm-mode along with Service Discovery, I think it would be great if you can attach logs from manual testing results of overlay networking in windows platform which we can use as a reference point for further development.

**Comment by msabansal** [comment]
@mavenugo I have been side tracked by some other P0 issues which are taking up a lot of my time. I will get this done ASAP (I am expecting by EOD tomorrow)

**Comment by msabansal** [comment]
Our scenario based CI test results:

```
PS C:\Windows\system32> C:\Tools\HNSCI.ps1 -remoteMachine 10.123.176.114 -toolsdir C:\Tools\
Describing HNS Network and Endpoint tests
   Context Validate NAT Networks
    [+] Should be able to build IIS Image 2.63s
    [+] Should Publish all ports 5.58s
    [+] Should Publish specific port 3.07s
    [+] Should be able to ping external host 1.83s
    [+] Validate hair pinning works 32.21s
    [+] Validate service discovery 11.03s
    [+] Should work with transparent network after service restart 7.67s
   Context Validate Transparent Networks
    [+] Should able to create single Transparent network. 7.01s
    [+] Should able to create multiple Transparent network. 7.14s
    [+] Should be able to ping external host 11.42s
    [+] Should able to communicate across containers. 13.95s
    [+] Should able to communicate across containers with non zero vlan. 13.91s
   Context Validate L2Bridge Networks
    [+] Should able to communicate across containers. 14.04s
```

sd

**Comment by mavenugo** [comment]
thanks @msabansal .

@mrjana as discussed, this commit : https://github.com/docker/libnetwork/pull/1530/commits/c5d2615733704c003be45f522ee5aee0c919ba0f brings in the change to the default VXLAN-id to 4096. It shouldn't impact any functionality. Just bringing this to your attention.

**Comment by msabansal** [comment]
Logs for creating a service scaled to two nodes is at https://gist.github.com/msabansal/d541623579ae271a699833e026745db5

**Comment by msabansal** [comment]
I will rebase to fix the conflict

**Comment by mavenugo** [comment]
@msabansal thanks a lot. By logs, I meant the outputs for the commands used and the final result of multiple containers pinging each other across nodes using swarm-mode.

**Comment by msabansal** [comment]
@mavenugo Ok doing that after I fix this conflict.

**Comment by mavenugo** [comment]
@msabansal changes LGTM.

There is another conflict with service_linux.go. can you pls resolve it asap ?

**Comment by msabansal** [comment]
@mavenugo I am working on it. I see SD break once I cherry pick and resolve. Trying to figure out why

**Comment by msabansal** [comment]
Logs:
```
PS C:\Windows\system32> $host1=New-PSSession -ComputerName WIN-8VTJOJS3FTS -Credential $credential
PS C:\Windows\system32> $host2=New-PSSession -ComputerName WIN-VICMHIUNSJC -Credential $credential
PS C:\Windows\system32> icm -Session $host1 -Command {ipconfig}

Windows IP Configuration


Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::4c2d:ece3:61bb:bb92%10
   IPv4 Address. . . . . . . . . . . : 172.18.48.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : corp.microsoft.com
   IPv6 Address. . . . . . . . . . . : 2001:4898:e0:6f:c929:2978:32c3:c33f
   Link-local IPv6 Address . . . . . : fe80::c929:2978:32c3:c33f%7
   IPv4 Address. . . . . . . . . . . : 10.123.176.114
   Subnet Mask . . . . . . . . . . . : 255.255.254.0
   Default Gateway . . . . . . . . . : fe80::200:5eff:fe00:205%7
                                       10.123.176.1

Ethernet adapter Ethernet 2:

   Connection-specific DNS Suffix  . : corp.microsoft.com
   IPv6 Address. . . . . . . . . . . : 2001:4898:e0:6f:1853:d8ff:6b93:878b
   Link-local IPv6 Address . . . . . : fe80::1853:d8ff:6b93:878b%5
   IPv4 Address. . . . . . . . . . . : 10.123.177.230
   Subnet Mask . . . . . . . . . . . : 255.255.254.0
   Default Gateway . . . . . . . . . : fe80::200:5eff:fe00:205%5
                                       10.123.176.1

Tunnel adapter isatap.corp.microsoft.com:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : corp.microsoft.com

Tunnel adapter isatap.{E66DB1B2-B834-491E-A3EA-5FA7C368CE23}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
PS C:\Windows\system32> icm -Session $host1 -Command {docker swarm init --advertise-addr=10.123.177.230 --listen-addr=10.123.177.230:2377}
Swarm initialized: current node (8gtlfpt2dactdk539k7mblxpd) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-2ah5w4aaya2uloewko2jl56j2f2qpixhihcpimvxqv9laku46r-7dw7mi4e5zn4d15ra4xwvianb \
    10.123.177.230:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

PS C:\Windows\system32> icm -Session $host2 -Command {docker swarm join --token SWMTKN-1-2ah5w4aaya2uloewko2jl56j2f2qpixhihcpimvxqv9laku46r-7dw7mi4e5zn4d15ra4xwvianb 10.123.177.230:2377}
This node joined a swarm as a worker.
PS C:\Windows\system32> icm -Session $host1 -Command {docker network create -d overlay overlaynet}
2kwkcr0zye0v49u9vdqklbxbt
PS C:\Windows\system32> icm -Session $host1 -Command { docker service create --name=s1 --endpoint-mode dnsrr --network=overlaynet nanoserver:latest powershell -command "& {echo sleep; sleep 3600;}" }
4gnky386zkd3j7vjjeuaistt6
PS C:\Windows\system32> icm -Session $host1 -Command {docker service scale s1=2}
s1 scaled to 2
PS C:\Windows\system32> icm -Session $host1 -Command {docker service ps s1}
ID                         NAME  IMAGE              NODE             DESIRED STATE  CURRENT STATE                    ERROR
30xz6k6s4uxr7sj1g0169iduq  s1.1  nanoserver:latest  WIN-8VTJOJS3FTS  Running        Starting less than a second ago
bcyr96uw6f8xz14m4odmz6ifd  s1.2  nanoserver:latest  WIN-VICMHIUNSJC  Running        Preparing 1 second ago
PS C:\Windows\system32> icm -Session $host1 -Command {docker service ps s1}
ID                         NAME  IMAGE              NODE             DESIRED STATE  CURRENT STATE           ERROR
30xz6k6s4uxr7sj1g0169iduq  s1.1  nanoserver:latest  WIN-8VTJOJS3FTS  Running        Running 1 second ago
bcyr96uw6f8xz14m4odmz6ifd  s1.2  nanoserver:latest  WIN-VICMHIUNSJC  Running        Starting 3 seconds ago
PS C:\Windows\system32> icm -Session $host1 -Command {docker ps }
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
51df81a59889        nanoserver:latest   "powershell -comma..."   17 seconds ago      Up 15 seconds                           s1.1.30xz6k6s4uxr7sj1g0169iduq
PS C:\Windows\system32> icm -Session $host1 -Command {docker exec -it 51df81a59889 ping s1 }
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
    + CategoryInfo          : NotSpecified: (the input devic...d with 'winpty':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : WIN-8VTJOJS3FTS

PS C:\Windows\system32> icm -Session $host1 -Command {docker exec  51df81a59889 ping s1 -n 1}

Pinging s1 [10.0.0.3] with 32 bytes of data:
Reply from 10.0.0.3: bytes=32 time=1ms TTL=128

Ping statistics for 10.0.0.3:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 1ms, Average = 1ms
PS C:\Windows\system32>

PS C:\Windows\system32> icm -Session $host2 -Command {docker ps }
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
212cd1e1f081        nanoserver:latest   "powershell -comma..."   About a minute ago   Up About a minute                       s1.2.bcyr96uw6f8xz14m4odmz6ifd
PS C:\Windows\system32> icm -Session $host2 -Command {docker exec 212cd1e1f081 ping s1 -n 1 }

Pinging s1 [10.0.0.2] with 32 bytes of data:
Reply from 10.0.0.2: bytes=32 time<1ms TTL=128

Ping statistics for 10.0.0.2:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

Please note that SD is not working for me after merge(/rebase). We will have to fix it after the merge

**Comment by mavenugo** [comment]
CI Green. LGTM.

@msabansal thanks for also sharing the results. We have to work towards adding overlay specific IT to catch issues early. We could introduce these tests in docker/docker (thanks to the new swarm-mode IT cases).

**Pull request merged**
