### PR TITLE
Backport fix to 17.03

### PR DESCRIPTION
**Pull request by fcrisciani**
Fixed cancelling method call to avoid go routine leaks

Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

### CODE REVIEW

**Comment by fcrisciani** [comment]
Not ready yet, looks like there is still something missing to handle the stacktrace reported above

**Comment by aaronlehmann** [comment]
I'm confused - is the problem with the backport, or is the stack trace in https://github.com/docker/libnetwork/pull/1784#issuecomment-305038056 unrelated to what was fixed here?

**Comment by fcrisciani** [comment]
@aaronlehmann sorry for the confusion, but I will group here all the backports for all the fixes for the goroutine leaks.
The fix are 3:
1) (already merged in master) wrongful rewrite of the cancelList for the watch of the endpoint_table
2) add return to the handleTableEvents
3) close the netlink socket and return of the watchMiss goroutine

**Comment by fcrisciani** [comment]
Wait for the master one to be reviewed and accepted:

- https://github.com/docker/libnetwork/pull/1787
- https://github.com/docker/libnetwork/pull/1786

**Comment by fcrisciani** [comment]
This commit covers:
https://github.com/docker/libnetwork/pull/1787
https://github.com/docker/libnetwork/pull/1786
https://github.com/docker/libnetwork/pull/1789
https://github.com/docker/libnetwork/pull/1795

**Comment by fcrisciani** [comment]
@mavenugo this is my side of the backport, you will notice that I mention 4 PR but I have 5 commits, the reason is that the logic for the coreCancelFuncs needed for avoiding the leak was part of this PR: https://github.com/docker/libnetwork/pull/1735 that we are not backporting

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
