### PR TITLE
Added maximum egress bandwidth qos for Windows

### PR DESCRIPTION
**Pull request by darrenstahlmsft**
This adds QoS policies to the Windows driver passed via a generic option. 

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by jhowardmsft** [comment]
@mrjana @mavenugo You guys OK with this? We need this merged and a revendor to move forward with completing some TP5 scenarios.

**Comment by mavenugo** [comment]
@jhowardmsft is this needed for 1.11 release ? if not, we can do a separate vendor-in from libnetwork master to docker master.

we are working on 1 currently from 1.11 from 0.7 branch of libnetwork.

**Comment by jhowardmsft** [comment]
@mavenugo Not for 1.11, but is for TP5.

**Comment by jhowardmsft** [comment]
@mavenugo Checking where we are on this as the TP5 deadline is looming, and we still have a re-vendor and a docker/docker PR to merge after this. Thanks :)

**Comment by mavenugo** [comment]
LGTM

**Comment by darrenstahlmsft** [comment]
@mavenugo Thanks! Is there a plan for a revendor into Docker master soon? I've got a PR waiting to leverage this in Docker.

**Comment by mavenugo** [comment]
@darrenstahlmsft sure. we can vendor in the master from libnetwork to docker master. There were few changes that came in recently in libnetwork master and we have to make sure that it aligns well with docker master.
cc @mrjana

**Pull request merged**
