### PR TITLE
etchosts: include the container's IPv6 address if available

### PR DESCRIPTION
**Pull request by kdomanski**
Partially addresses moby/moby#13228

This fixes a very real usecase for me. I'd like to run an application that misbehaves if its hostname doesn't resolve to its listen address. The resolver find the hostname in `/etc/hosts` and returns only the IPv4 address.

### CODE REVIEW

**Comment by kdomanski** [comment]
PTAL @thaJeztah @selansen

**Comment by selansen** [comment]
could you pls write small test cases that validates IPV4 and IPV6 ?
Changes looks good to me.

**Comment by kdomanski** [comment]
Done.

**Comment by selansen** [comment]
@trapier @euanh @thaJeztah Can you PTAL?
Prefer one more eye to review.

**Comment by trapier** [comment]
Not available on this one.

**Comment by kdomanski** [comment]
ping @thaJeztah

**Comment by thaJeztah** [comment]
ping @arkodg @euanh ptal

**Pull request merged**
