### PR TITLE
Fix typos and formatting in docs. Add Godoc badge.

### PR DESCRIPTION
**Pull request by dave-tucker**
Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by mrjana** [comment]
@dave-tucker Tried look at the godoc package and the package doc doesn't seem to rendering as expected. Can you take a look?

**Comment by dave-tucker** [comment]
@mrjana, looks fine to me...  I'm using `godoc -http=:6060`
Then browsing to:  http://localhost:6060/pkg/github.com/docker/libnetwork/

napkin 15-04-15 6 08 13 pm

**Comment by mrjana** [comment]
@dave-tucker The page in github when you click on the godoc badge doesn't look right

**Comment by dave-tucker** [comment]
@mrjana ah ha! Yes that's what this commit will fix... those docs are generated from `master` where the code block above isn't indented properly.

**Comment by mavenugo** [comment]
Thanks Dave. LGTM.

**Comment by nerdalert** [comment]
LGTM

**Pull request merged**
