### PR TITLE
weighted scheduling methods constants for ipvs

### PR DESCRIPTION
**Pull request by jdrahos**
Small change related to #2452 
Two new scheduling method constants were added for ipvs

### CODE REVIEW

**Comment by arkodg** [comment]
@jdrahos thanks for raising this PR, can you please add the corresponding constants in `ipvs/ipvs_test.go`

**Comment by jdrahos** [comment]
@arkodg added the constants to the test as requested. The CI has failed but it looks like it is not related to the change. Running the tests locally is passing so assume this is being a flaky test or something.

**Comment by jdrahos** [comment]
Thank you @arkodg for your help, the CI passed after re-run.

**Comment by arkodg** [comment]
cc @selansen

**Pull request merged**
