### PR TITLE
Speedup etchosts delete

### PR DESCRIPTION
**Pull request by LK4D4**
Benchmarks comparison:
```
Benchmark results:
benchmark           old ns/op     new ns/op     delta
BenchmarkDelete     4315186       2245829       -47.96%

benchmark           old allocs     new allocs     delta
BenchmarkDelete     4645           10             -99.78%

benchmark           old bytes     new bytes     delta
BenchmarkDelete     1590011       4832          -99.70%
```
That operations was 55% of time of container stop in Docker project.

### CODE REVIEW

**Comment by LK4D4** [comment]
Looks like circleCI can't clone repo.

**Comment by mavenugo** [comment]
@LK4D4 hmm.. lemme check.

**Comment by LK4D4** [comment]
ping @mavenugo @mrjana 
easy merge :)

**Comment by mavenugo** [comment]
@LK4D4 oops... sorry about the delay. completely consumed by 1.9.0 issues.

**Comment by calavera** [comment]
very nice @LK4D4 :metal:

**Comment by mavenugo** [comment]
thanks @LK4D4. Awesome improvement.
LGTM.

**Comment by thaJeztah** [comment]
Do we have an issue tracking this in docker/docker?

**Comment by LK4D4** [comment]
ping @mrjana @aboch

**Comment by LK4D4** [comment]
@thaJeztah no, there is no issue

**Comment by aboch** [comment]
LGTM

**Pull request merged**
