### PR TITLE
Allow libnetwork to compile on freebsd

### PR DESCRIPTION
**Pull request by miguel250**
libnetwork should be able to compile on freebsd after #186 is merged with this changes.

### CODE REVIEW

**Comment by mavenugo** [comment]
@miguel250 PTAL https://github.com/docker/libnetwork/pull/770#issuecomment-159467279. Can you please work with @runcom and make sure #770 doesnt have negative impact on FreeBSD ?

**Comment by runcom** [comment]
I think I can just add the freebsd build tag to my pr  and if it was supported I'm sure it will again

**Comment by runcom** [comment]
@mavenugo I've updated my PR, @miguel250 can you try my patch https://github.com/runcom/libnetwork/commit/0b750b132a4e8e74da61a2d0e502305982521718 and see if it's ok on freebsd?

**Comment by miguel250** [comment]
@mavenugo I was able to build it on freebsd with @runcom but with no issues. I included  #186, #770 and this patch to create a successful build.

**Comment by aboch** [comment]
LGTM

**Comment by miguel250** [comment]
Hi I rebased this PR with master.

**Comment by mavenugo** [comment]
Thanks @miguel250 LGTM

**Pull request merged**
