### PR TITLE
Enable embedded DNS server on network connect to a user defined network

### PR DESCRIPTION
**Pull request by sanimej**
Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
relates to https://github.com/docker/docker/issues/19376.

**Comment by tiborvass** [comment]
Ping @mavenugo @sanimej any news on this? this is a p0 on docker

**Comment by mrjana** [comment]
Thanks @sanimej for taking care of all the offline comments. LGTM

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
