### PR TITLE
Embedded DNS server should resolve only in docker network domain

### PR DESCRIPTION
**Pull request by sanimej**
Fixes [docker/docker #19448] (https://github.com/docker/docker/issues/19448)

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
couple of comments
1. docker allows `.` in the container name and hence we should be able to resolve the container name as is.
2. current logic is also broken in this use-case. Need to be fixed as well.

**Comment by sanimej** [comment]
Yes. The current resolution logic uses the `.` for sub-domain separation. It needs to be changed since we allow `.` in the service name.

**Comment by sanimej** [comment]
@mavenugo Changed the resolution logic to account for the '.' in service name.. PTAL

**Comment by mavenugo** [comment]
LGTM.

It would be good to add IT for these cases. We can also add it in docker/docker if it is easier.
But please add them to avoid any regressions in the future.

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
