### PR TITLE
Fix test using com.docker.network.mtu

### PR DESCRIPTION
**Pull request by thaJeztah**
This should be `com.docker.network.driver.mtu`

fixes https://github.com/docker/libnetwork/issues/1906

ping @abhinandanpb PTAL

### CODE REVIEW

**Comment by abhinandanpb** [comment]
LGTM

**Comment by fcrisciani** [comment]
@thaJeztah should we investigate why the test is passing?

**Comment by thaJeztah** [comment]
Yes, if you have thoughts, definitely 👍

**Comment by abhinandanpb** [comment]
since its an option I dont there is a check to verify.

**Comment by fcrisciani** [comment]
don't have much context in this area, but I guess if the option is for a driver would have to contain the `.driver.` string I imagine, in that case I would say that we do not validate at the level of libnetwork, but if that string is not there, will probably mean that is a libnetwork option, so we can actually validate it and return an error if not recognized. What do you guys think? @thaJeztah @abhinandanpb

**Comment by abhinandanpb** [comment]
I think for this test if we want to check if mtu is set appropriately which would also mean we would have validated the option - we can add a check ```network.mtu ==  1600``` and ```network``` is returned by ```controller.NewNetwork```

**Comment by fcrisciani** [comment]
I was more referring as a general approach more than the test itself, how to avoid to accept options that won't create any effect but will simply be silently ignored. As a first line of defense check that the option at least exists and if not return an error.

**Comment by vieux** [comment]
LGTM

**Comment by thaJeztah** [comment]
@fcrisciani anything you want me to change in this PR, or good to go?

**Pull request merged**
