### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by liubin**
Signed-off-by: bin liu <liubin0329@gmail.com>

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by dave-tucker** [comment]
LGTM, @liubin can you please rebase?

**Comment by liubin** [comment]
Hi, @dave-tucker , I have rebased it, please check again.

Thanks,
Bin

**Comment by dave-tucker** [comment]
@mrjana @mavenugo ready to merge this one?

**Comment by mavenugo** [comment]
Thanks. LGTM.

**Pull request merged**
