### PR TITLE
make libnetwork compile on freebsd (again)

### PR DESCRIPTION
**Pull request by kvasdopil**
Signed-off-by: Alexey Guskov <lexag@mail.ru>

### CODE REVIEW

**Comment by thaJeztah** [comment]
@mavenugo @mrjana wondering what the status is here, I'd hate to see the FreeBSD work stalling :smile:

**Comment by mrjana** [comment]
@kvasdopil You may need to rebase and recheck if freebsd build is working again since we have made a few more additions to sandbox interface since you created this PR

**Comment by kvasdopil** [comment]
@mrjana Sorry for the delay. I've updated the PR.

**Comment by mrjana** [comment]
Thanks @kvasdopil. LGTM

**Comment by mavenugo** [comment]
LGTM

**Comment by thaJeztah** [comment]
Great! thanks @kvasdopil !

**Pull request merged**
