### PR TITLE
Show IP list of service endpoint in docker service info.

### PR DESCRIPTION
**Pull request by vijayendrabvs**
Closes #14781

### CODE REVIEW

**Comment by dsampath** [comment]
+1

**Comment by aboch** [comment]
Holding on this, as we have not thought yet what the proper info hierarchy should be for endpoint (for example, should we expose the endpoint interfaces ? and then the stats ?)

Given it is a public API, I'd prefer to reserve some time to think about the proper structure.

**Comment by vijayendrabvs** [comment]
Not exposing endpoint info would render libnetwork incapable of supporting fine grained network operations on docker containers. APIs should be as powerful as they can be. Authorization (ACLs/policies) should be where filters are applied to control what data is exposed and what isn't. Taking this approach will also help in enabling easier migration in future and not break backward compatibility once requests for API customizations start coming in with greater adoption.

**Comment by mavenugo** [comment]
@vijayendrabvs the issue is not about not exposing the endpoint info. Rather, it is about having proper structure to the data like @aboch suggested. 

In this PR, you have added just the IP-Address list. Though it satisfies your need, it is not generic enough that will keep the API cleaner and used for different use-cases. 

So, in order to make this right, can you add all the info that you get from endpointInfo instead of just the ip-address ? (this includes gateway, mac-address, ipv6, etc...)

**Comment by vijayendrabvs** [comment]
@mavenugo Thanks for pitching in to review this! I'd be happy to add the other fields as well - will submit a new patch at the earliest.

**Comment by aboch** [comment]
Since this PR was opened, considerably changes happened. Multihost networking exited experimental mode with several modification to the model: No more services. Also network specific docker rest API are getting handled directly in docker project.

Therefore I am closing this PR as it was opened to address an issue on the experimental MH networking in docker.

**Pull request closed without merging**
