### PR TITLE
Libnetwork bridge to handle MTU option

### PR DESCRIPTION
**Pull request by aboch**
- This address one of the requirements of Issue #78
- Taken care of @mrjana  comments
Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by mrjana** [comment]
@aboch actually you don't need to set the mtu of the bridge at all. It will assume the mtu of the lowest mtu of all the ports in the bridge

**Comment by mrjana** [comment]
Rebase please

**Comment by mrjana** [comment]
LGTM

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
