### PR TITLE
Cherry-picks for release/v0.8 branch

### PR DESCRIPTION
**Pull request by aboch**

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch why is this https://github.com/docker/libnetwork/pull/1515/commits/cad96469a97e812755d78b6857535a90df1f54db critical ?

**Comment by mavenugo** [comment]
just a minor comment above. otherwise LGTM

**Comment by aboch** [comment]
It is a regression introduced in 1.2.x

**Comment by mavenugo** [comment]
thanks @aboch. LGTM

**Pull request merged**
