### PR TITLE
Improve interface order

### PR DESCRIPTION
**Pull request by cziebuhr**
Solves #2093 b). PR is based on #2103.

### CODE REVIEW

**Comment by ctelfer** [comment]
The changes to the interface comparison LGTM.  Might be worth amending the last commit with a cut-and-paste of the things we discussed in #2093 for reference.  Or maybe put it as a comment to the Less() method.

**Comment by cziebuhr** [comment]
PR has been updated

**Comment by ctelfer** [comment]
@fcrisciani @abhi @ddebroy   Would any of you mind reviewing and do you think we should add a unit test case for it as well?

**Comment by cziebuhr** [comment]
bump

**Comment by ddebroy** [comment]
The code LGTM. It would be great if unit-tests can be added that verifies the `Less` and enumeration order follows expected ordering.

**Comment by cziebuhr** [comment]
Unit tests have been adapted to the new ordering rules.

**Comment by ctelfer** [comment]
Thanks for the PR!  Sorry it took so long.  I suppose the next step is to now expose the priority fields in moby as configuration parameters.

**Comment by cziebuhr** [comment]
I don't think I can handle the next step myself. Is there any process other than keeping #2093 open to let someone continue who is more familiar with changing APIs?

**Pull request merged**
