### PR TITLE
Pass the vxlan port in network endian order

### PR DESCRIPTION
**Pull request by sanimej**
Signed-off-by: Santhosh Ram Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
Good catch. LGTM.

**Comment by aboch** [comment]
I see a clear bug in NativeEndian() function in the vendored netlink code: `nativeEndian` is always set to  `binary.LittleEndian` no matter what.

Then I checked the latest netlink code in github and I see that the issue was fixed.
This is the [commit](https://github.com/vishvananda/netlink/commit/9cff81214893f3b52dfc307a45669eb7f96fcada) which fixed it.

Can we try pulling the latest netlink in libnetwork instead ?

**Comment by aboch** [comment]
BTW, I doubt you are running on a bigendian machine, so issue should still be there with latest netlink.

**Comment by mavenugo** [comment]
@aboch good catch on the netlink dependancy issue. It is now resolved via https://github.com/docker/libnetwork/pull/448. I think this PR works now across platform.

**Comment by aboch** [comment]
LGTM

**Comment by sanimej** [comment]
Would have better if the kernel code does the translation to network order. Its done for the vni for example. The problem with the port will affect other user space tools as well.  iproute2 package code changes the port to the network order, similar to this change.

**Pull request merged**
