### PR TITLE
Remove system thread locks from tests.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
@calavera can you please add some comment on the reason to remove these locks from tests ?
They are added for a good reason.

**Comment by calavera** [comment]
> They are added for a good reason.

What's that reason?

As far as I know, we should only lock the thread when we switch between namespaces. That's already covered in:

https://github.com/docker/libnetwork/blob/9da326c85471a0a6eec902e1ce0aa2a9d58aeb19/netutils/test_utils.go#L25
https://github.com/docker/libnetwork/blob/0e7322b4851c2d47e4998fffd9661a566808b8b4/sandbox/namespace_linux.go#L173
and
https://github.com/docker/libnetwork/blob/0e7322b4851c2d47e4998fffd9661a566808b8b4/sandbox/namespace_linux.go#L246

Being honest, the fact that those tests lock the os thread and never unlock it scares the hell out of me. They seem to be in place to avoid race conditions in the code, which scares me even more.

This one, for instance, was locking the thread inside a loop :confused: 

https://github.com/docker/libnetwork/pull/327/files#diff-9b1328f1a3ef3edcaa77554528154dedL50

**Comment by mrjana** [comment]
@calavera These locks are there only for the reason where the tests are run outside the container in most cases (and needed all the time for sandbox tests). The reason why they are there is because we run most of  the network tests in a separate network namespace and lock the go routine to the OS thread anyways. Now golang has limitation in that it doesn't accommodate recursively locking OS thread properly. So when the test code locks the OS thread and calls the sandbox api, the sandbox api also locks the OS thread and then unlocks the OS thread. But the unlock that is happening inside the sandbox api will also unlock from the lock that we had in the test code which will make the test code do weird things if the go routine running the test has been moved to different `M`.

The thing that you need to understand about `LockOSThread` is that it doesn't serialize anything. It just locks the calling go routine to be not scheduled to a different `M`. So if there are two parallel goroutines running on two different `M`s and they lock the OS thread, they will still run in parallel.

> Being honest, the fact that those tests lock the os thread and never unlock it scares the hell out of me. They seem to be in place to avoid race conditions in the code, which scares me even more.

With the above explanation hopefully there is no more reason  to get scared :-)

**Comment by mrjana** [comment]
@calavera Let me know what you want to do with this PR.

**Pull request closed without merging**
