### PR TITLE
Don't allow passing EnableIPv6 as a driver option (a label)

### PR DESCRIPTION
**Pull request by aidanhs**
docker/docker#17513

Per point two at the end of https://github.com/docker/docker/pull/17513#issuecomment-164032291

### CODE REVIEW

**Comment by aidanhs** [comment]
Looks like this isn't going to be as simple as I hoped, looks like lots of tests etc need changing.

**Comment by aboch** [comment]
>Looks like this isn't going to be as simple as I hoped, looks like lots of tests etc need changing.

I don't think so, this function setter is not used in tests. For now CI is just complaining about code formatting. Actually about `netutils` which no longer needs to be imported.

**Comment by aidanhs** [comment]
Some key notes:
 - I added `NetworkOptionEnableIPv6`, which is a setter for ipv6 on a network.
 - I added the `--ipv6` flag to `client/network.go`, which required changes to api/api.go. While I was there, I fixed the broken handling of netlabel.Internal (it previously only checked if the value existed in the map, rather than actually checking if it's true or false).
 - `netlabel.Internal` is now recognised in `NetworkOptionGeneric` for consistency with `netlabel.EnableIPv6` (note: nothing to do with labels)
 - `netlabel.EnableIPv6` is now *not* recognised as a label (i.e. when passed in `NetworkOptionDriverOpts`)
 - a test was removed from api_test.go as it was a duplicate
 - NetworkOptionGeneric now merges settings rather than overwriting them. This means you should be able to freely reorder things like ipv6 and internal setters without their entries being clobbered in GenericData

I began trying to make the usage of GenericData consistent (docker uses it for string->string labels, but libnetwork tests use it for pretty much anything they feel like) but gave up because there was just too much.

**Comment by aboch** [comment]
LGTM

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
