### PR TITLE
Add TestSandboxInfoEqual in sandbox_test.go

### PR DESCRIPTION
**Pull request by fmzhen**
Add  TestSandboxInfoEqual in driverapi_test.go

Signed-off-by: Mingzhen Feng <fmzhen@zju.edu.cn>

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by mavenugo** [comment]
Can you please rebase the change and modify the test based on the new sandbox package ?

**Comment by fmzhen** [comment]
i have fixed it up.  ping @mavenugo

**Comment by aboch** [comment]
LGTM

**Comment by mavenugo** [comment]
Thanks @fmzhen

**Pull request merged**
