### PR TITLE
Fix parseIP error when parseIP before get AddressFamily

### PR DESCRIPTION
**Pull request by icefed**
Signed-off-by: Tom Zhao <zlwangel@gmail.com>

Fix: https://github.com/docker/libnetwork/issues/2431

### CODE REVIEW

**Comment by arkodg** [comment]
@icefed thanks for fixing this issue

thinking if something like this would be cleaner

initialize `AddressFamily` before the loop starts
```
s.AddressFamily = syscall.AF_INET
```

and when we receive `s.AddressFamily` we can recompute `s.Address`
```
                case ipvsDestAttrAddressFamily:
                       s.AddressFamily = native.Uint16(attr.Value)
                       // Recompute s.Address
                       fallthrough
		case ipvsSvcAttrAddress:
			ip, err := parseIP(attr.Value, s.AddressFamily)
			if err != nil {
				return nil, err
			}
			s.Address = ip
```

**Comment by arkodg** [comment]
can we also add a test case for this, so we catch it, if its 100% reproducible

**Comment by icefed** [comment]
> @icefed thanks for fixing this issue
> 
> thinking if something like this would be cleaner
> 
> initialize `AddressFamily` before the loop starts
> 
> ```
> s.AddressFamily = syscall.AF_INET
> ```
> 
> and when we receive `s.AddressFamily` we can recompute `s.Address`
> 
> ```
>                 case ipvsDestAttrAddressFamily:
>                        s.AddressFamily = native.Uint16(attr.Value)
>                        // Recompute s.Address
>                        fallthrough
> 		case ipvsSvcAttrAddress:
> 			ip, err := parseIP(attr.Value, s.AddressFamily)
> 			if err != nil {
> 				return nil, err
> 			}
> 			s.Address = ip
> ```

Hi @arkodg, `ipvsSvcAttrAddress Value` has 16 bytes, we can not use `ipvsDestAttrAddressFamily Value`(2 bytes) to recompute Address. So, it will not work.

**Comment by icefed** [comment]
> LGTM, can we also add a test case please

Sorry for miss this, I will add test later.

**Comment by icefed** [comment]
hi @arkodg, I added tests for ipv6 and local passed, I don't know `circleci: unit-tests` failed.

**Comment by arkodg** [comment]
@icefed can you please rebase to the latest `master`, I've taken care of the unit-tests regression by  reverting a commit

**Comment by thaJeztah** [comment]
@arkodg looks like this was rebased; CI is green now

**Pull request merged**
