### PR TITLE
Simplify the code in the RegisterSubnet method of ipallocator.

### PR DESCRIPTION
**Pull request by junxu**

### CODE REVIEW

**Comment by aboch** [comment]
Thank you for cleaning up this.

LGTM

**Comment by mavenugo** [comment]
@junxu the CircleCI tests failed, but not reporting the error (It is NOT due to your fix). We had resolved the failure recently. Can you please rebase your changes and push it again so that we can let the circle-ci succeed ?

**Comment by junxu** [comment]
@mavenugo I have done the rebase, please check again, thanks!

**Comment by mavenugo** [comment]
Thanks @junxu LGTM.

**Pull request merged**
