### PR TITLE
Add missing sandboxes routes

### PR DESCRIPTION
**Pull request by tmakita**
Signed-off-by: Toshiaki Makita <makita.toshiaki@lab.ntt.co.jp>

---
Note: Docker has the same problem in api/server/server_experimental_unix.go.
"docker service attach" doesn't work.

### CODE REVIEW

**Comment by mavenugo** [comment]
@tmakita thanks. LGTM.

**Comment by abronan** [comment]
Was just wondering why I couldn't curl the socket at `/sandboxes` while testing the changes in experimental. Makes sense now :+1:

**Comment by aboch** [comment]
LGTM

**Comment by aboch** [comment]
Thanks @tmakita !

**Pull request merged**
