### PR TITLE
[18.03 backport] Cleanup the cluster provider when the agent is closed

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/docker/libnetwork/pull/2307 for the 18.03 branch

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @mavenugo @euanh PTAL

**Comment by selansen** [comment]
looks like TestNetworkDBIslands failing consistently ( Same failure on other backport too )

**Comment by thaJeztah** [comment]
```
--- FAIL: TestNetworkDBIslands (75.83s)
	Location:	networkdb_test.go:838
	Error:		"map[4ac5b1d46794:4ac5b1d46794 79fd1a707bd6:79fd1a707bd6]" should have 3 item(s), but has 2
		

	Location:	networkdb_test.go:839
	Error:		"map[2624cc77ef1d:2624cc77ef1d]" should have 0 item(s), but has 1
		

FAIL
```

Looks like it may be flaky https://github.com/docker/libnetwork/pull/2240#issuecomment-407822195

**Comment by thaJeztah** [comment]
Don't have permissions to trigger CI in this repo 😕

**Comment by selansen** [comment]
Like I mentioned , I did see same error failure in my PRs few times in the past.
I think we can merge it adding a note on this test case.

**Comment by kylewuolle** [comment]
ping @mavenugo @euanh !

**Pull request merged**
