### PR TITLE
Updating memberlist to v0.1.0

### PR DESCRIPTION
**Pull request by fcrisciani**
Vendoring memberlist to first available release

Signed-off-by: Flavio Crisciani <flavio.crisciani@docker.com>

### CODE REVIEW

**Comment by fcrisciani** [comment]
I saw that in networkdb we are using the lamport clock of serf, in the latest release there is an interesting fix that handles the case where the CAS operation fails and retry the operation till is suceed.
For more info: https://github.com/hashicorp/serf/commit/39c8c6a2a4fb88c54a54b07c9e906aaa94a44cc6

**Comment by aboch** [comment]
LGTM

**Comment by sanimej** [comment]
@fcrisciani The lamport clock fix was made way back in 2013 and its already in the vendored in code.

Does the memberlist bump fix any specific issue relevant for us ?

**Comment by fcrisciani** [comment]
@sanimej you were right about the serf, I removed the vendoring for it.

For what concerns memberlist, this is the first release available, I see +100 commits on top of our last vendoring.

**Pull request merged**
