### PR TITLE
[18.09 backport] Cleanup the cluster provider when the agent is closed

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/docker/libnetwork/pull/2307 for the  18.09 branch

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @mavenugo @euanh PTAL

**Comment by selansen** [comment]
@thaJeztah ,
I see test failure on TestNetworkDBIslands.  Don't think its related to this one like changer.
do we need re run CI one more time ?

**Comment by thaJeztah** [comment]
Force-pushed to re-run CI (flaky test)

ping @mavenugo @euanh PTAL 🙏

**Comment by kylewuolle** [comment]
> Force-pushed to re-run CI (flaky test)
> 
> ping @mavenugo @euanh PTAL 🙏

Can you try doing the same on this one too! 
https://github.com/docker/libnetwork/pull/2353
Thanks!

**Pull request merged**
