### PR TITLE
Add support for NetworkAllocate and NetworkFree in remote driver

### PR DESCRIPTION
**Pull request by mavenugo**
Also added an API to return list of builtin network drivers

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @mrjana

**Comment by aboch** [comment]
Does this replace #1306 ?

**Comment by mavenugo** [comment]
@aboch yes.

**Comment by aboch** [comment]
LGTM

**Pull request merged**
