### PR TITLE
Migrate controller to use RWMutex

### PR DESCRIPTION
**Pull request by aboch**
So to avoid locking the controller for the read only operations

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch is this PR addressing a specific issue in docker/docker ?

**Comment by aboch** [comment]
@mavenugo No, this is to improve concurrent operations.

**Comment by fcrisciani** [comment]
Went through the changes and LGTM, but it's better is also another pair of eyes take a look

**Comment by vieux** [comment]
@fcrisciani I rebased this one.
@abhinandanpb can you take a look ?

**Comment by abhinandanpb** [comment]
LGTM

**Comment by fcrisciani** [comment]
@vieux considering the issues that we are finding in managing concurrent operations, I feel less ready to go ahead on this...

**Comment by vieux** [comment]
I understand, up to you, I'd suggest we close this one if we don't plan on merging to any time soon.

**Comment by fcrisciani** [comment]
not going to happen in the near future, closing for now

**Pull request closed without merging**
