### PR TITLE
Add Alessandro as a libnetwork maintainer

### PR DESCRIPTION
**Pull request by mrjana**
Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
:+1:
LGTM :-)

**Comment by thaJeztah** [comment]
If this is accepted, I think it would be consistent to add the "libnetwork" subsystem to the docker MAINTAINERS file as well, similar to libcontainer; https://github.com/docker/docker/blob/7c6cab6345a7398ebc95048418f379d43e9a00fd/MAINTAINERS#L437

**Comment by mavenugo** [comment]
ping @icecrime @LK4D4

**Comment by icecrime** [comment]
LGTM :+1:

**Pull request merged**
