### PR TITLE
bump docker/docker to master and unfork dependencies

### PR DESCRIPTION
**Pull request by thaJeztah**
This patch updates all dependencies to match what is used in moby/moby. Making the dependencies match what is used in that repository makes sure we test with the same version as libnetwork is later built with in moby.

This also gets rid of some temporary forks that were needed during the migration of Sirupsen/logrus to sirupsen/logrus.

ping @fcrisciani @abhi LMK if you think this is a good thing to do; I started this to just get rid of the forks, but noticed the version of the dependencies used here were very outdated, compared with what's used in Docker, so decided to try and bump those to what's currently used there.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like some changes are needed in the `dnet` tool that's used in the tests;

```
go build -o "bin/dnet-$GOOS-$GOARCH" ./cmd/dnet
# github.com/docker/libnetwork/cmd/dnet
cmd/dnet/dnet_windows.go:20: undefined: system.CreateEvent
Makefile:60: recipe for target 'cross-local' failed
make: *** [cross-local] Error 2
make: *** [circle-ci-cross] Error 2
```

**Comment by thaJeztah** [comment]
I'll need to make the same modifications as are made here; https://github.com/moby/moby/commit/e942513ac46656c3f54cd103e990e2b7bd5c2b14#diff-e1546f0e7fe0b238191ff0cb82342936

**Comment by thaJeztah** [comment]
Updated, all green now 👍

**Comment by fcrisciani** [comment]
Fixes: https://github.com/docker/libnetwork/issues/1899

**Comment by fcrisciani** [comment]
LGTM, but I would like also @mavenugo to take a look

**Comment by mavenugo** [comment]
For this change, If CI is happy, am happy :)

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
