### PR TITLE
fix bitseq set race condition

### PR DESCRIPTION
**Pull request by tianweidut**
This change will fix bitseq set race condition.  `h.Lock()` should
include `pushReservation` func, if not, another bitseq set maybe use
same `h.head` which will lead to generate two different containers use
same container ip in bridge network at the same time.

related: https://github.com/docker/libnetwork/issues/1740

Signed-off-by: liutianwei <liutianwei@douban.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
thanks @tianweidut for the patch. ping @aboch

**Comment by aboch** [comment]
Thanks @tianweidut for the issue.
This issue happens because the IPAM backing bitsequence for local scope drivers is no longer using a kv store. 

I had pushed #1625 for this. But given no issues were reported about this, I guess that is the reason it was not being looked closely by other maintainers.

We intentionally did not want to lock the header in the `set()` function, because the atomicity is provided by the datastore. So we just acquire a copy of the header, if somebody else was able to push an update to the store in the meantime, our push will fail with the retry error and we will repeat the procedure on top of the up-to-date state.

#1625 is therefore serializing the access to the handle only in case the datastore is missing.
It would be great if you could run your parallel test with #1623 changes. (In that PR I verify the parallel allocation via unit test over id manager)

**Comment by tianweidut** [comment]
@aboch  thanks for your reply.  I can reproduce `different containers use same ip` issue. more details is here: https://github.com/docker/libnetwork/issues/1740

**Comment by tianweidut** [comment]
@aboch  https://github.com/docker/libnetwork/pull/1625 is the better solution, could other maintainers review and merge it?  It will fix https://github.com/docker/libnetwork/issues/1740

**Comment by daicang** [comment]
https://github.com/docker/libnetwork/pull/1625/files from docker 17.10, libnetwork use a serial approach to pick from bitmap, but they still not recognize this racing problem

**Comment by daicang** [comment]
Fixed in https://github.com/docker/libnetwork/commit/a7df5629fdf345d9269372aec6cfc5431d9fc31b

**Comment by fcrisciani** [comment]
@tianquan23 closing this one not anymore relevant

**Pull request closed without merging**
