### PR TITLE
bridge,portmapper: custom docker-proxy path

### PR DESCRIPTION
**Pull request by runcom**
libnetwork change for https://github.com/docker/docker/pull/26882 based on @aboch's comment at https://github.com/docker/docker/pull/26882#discussion_r80364014

@aboch PTAL

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
ping @aboch @mavenugo @mrjana

**Comment by aboch** [comment]
LGTM

**Comment by runcom** [comment]
ping @mrjana @mavenugo :angel: :angel: :angel:

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
