### PR TITLE
DNS MX lookups will return an A record string response matching the query string

### PR DESCRIPTION
**Pull request by tya**
This PR will add DNS resolution for MX records.  Any MX record lookup will return an A record response matching the lookup string.

```
dig MX myapp # should return myapp.
dig myapp # should return IP of container
```

Each container can then potentially act as a mail server.

Signed-off-by: Ty Alexander ty.alexander@sendgrid.com

### CODE REVIEW

**Comment by aboch** [comment]
Please squash the two commits in one, they are both changing new code.

**Comment by tya** [comment]
@aboch commits have been squashed per you request.

**Comment by sanimej** [comment]
@tya Thanks for the PR. But the approach of treating every single container as offering mail service is not correct. Docker DNS server being an embedded server currently doesn't offer a UX to add custom entries. When such an UX is available it makes sense to allow creating an MX record. 

Specific to this implementation, its not correct to just return the query name in the reply. This will break external MX queries (for ex: dig MX microsoft.com)

**Comment by tya** [comment]
@sanimej Thank you for the follow up.  Do you have any suggestions on how I can get MX lookups to resolve using user defined network(s).  I am open to using a dns container such as https://github.com/aacebedo/dnsdock, but not sure how I can get a container to act as a DNS fallback after 127.0.0.11.  Static IP for the dnsdock perhaps?

Thanks you for your time and code review.

Would you like me to close out this pull request?

**Comment by sanimej** [comment]
@tya Here is one way you could do this.. Assuming you are using user defined networks, you can run dnsmasq (or some other DNS server) as a container in that network. You can use `--subnet` option of network create and `--ip` in the docker run to get a fixed IP for the DNS server. In dnsmasq you can add an MX record. In your client containers use `--dns` option to pass the DNS server container's IP.
In the resolv.conf you will see only 127.0.0.11. But embedded server will forward unresolved queries (like MX) to the external server, which is your DNS server. You can also configure the external nameservers in your DNS server so that all queries will get forwarded through that. Let me know if you face any issues in getting this to work.

Please go ahead and close this PR.

**Comment by tya** [comment]
@sanimej thanks again for the follow up.  Will try static ip approach on dns container for now.  Ideally I would like to avoid hard coding DNS ip and subnet but I can understand these are new and maturing features for libnetowrk.  Thanks again for your time. Closing PR.

**Pull request closed without merging**
