### PR TITLE
reserve the default gateway IP address if sharing the same subnet with host

### PR DESCRIPTION
**Pull request by mountkin**
If the user adds the physical interface to a bridge and configures Docker to use the same subnet as the host (start daemon with the -b parameter), the IP address of the default gateway might be in the IP pool of the allocator.
In such case we should exclude it from the IP pool. Otherwise the gateway IP may be assigned to a container, which will disrupt the host network.

The problem can be reproduced by:
- run the following script with your own network variables (gateway IP, interface name, IP addr, etc.)
```
#!/bin/bash
ip l add br1 type bridge
ip l set br1 up
ip ad flush dev eth0
ip ad add 192.168.122.122/24 dev br1
ip l set eth0 master br1 promisc on
ip r del default
ip r add default via 192.168.122.1 dev br1
arping -A -b -c 1 -I br1 192.168.122.122
```
- start docker daemon with `docker daemon -b br1`
- create some containers 

Signed-off-by: Shijiang Wei <mountkin@gmail.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks for the patch. PTAL https://github.com/docker/libnetwork/issues/489 and its associated PRs. the docker IPAM is undergoing some significant changes. lets try to address this PR in the context of the new IPAM. Shall we close this and open an issue instead so that we can track if we get a solution with the upcoming changes ?

**Comment by mountkin** [comment]
@mavenugo In the description of #525 I saw this line "Bridge driver not changed yet".
If in the future the bridge will use the IPAM driver I think this PR can be closed.

**Comment by mavenugo** [comment]
@mountkin yes. all the drivers and plugins, including the bridge driver will make use of the ipam driver. So, yes, i think we should close this PR.

**Comment by mountkin** [comment]
Okay, I'll close this and open an issue.

**Pull request closed without merging**
