### PR TITLE
Honor enableIPv6 network flag on IP allocation

### PR DESCRIPTION
**Pull request by aboch**
- If the flag is not set, do not query IPAM driver for IPv6 pool/addresses reservation, regardless whether they were was passed.

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
The changes looks reasonable.
But, you have to take care of upgrade cases. Hence, I think we should set the `enableIPv6` flag in the network automaticallly during unmarshal if an existing ipv6 subnet is specified by the user (ipam configuration).

**Comment by mavenugo** [comment]
ping @aboch

**Comment by aboch** [comment]
@mavenugo Addressed your comments. PTAL

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
