### PR TITLE
[17.09] Fix reapTime logic in NetworkDB + handle cleanup DNS for attachable container

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry-pick of https://github.com/docker/libnetwork/pull/1944 and https://github.com/docker/libnetwork/pull/1960 for 17.09

```
git checkout -b 17.09-backport-netdb-fix-reap upstream/bump_17.09
git cherry-pick -s -S -x 10cd98c56fb17737834c1031cad56a9932a266f4
git cherry-pick -s -S -x 3feb3aadf388d64bb8ea7e0a6614933d3d8b885a
git cherry-pick -s -S -x fbba555561bab4af332d6c1ee592976f16c609c3
```

Also included https://github.com/docker/libnetwork/pull/1985 and https://github.com/docker/libnetwork/pull/1991, which look to depend on this

```
# PR: https://github.com/docker/libnetwork/pull/1985
git cherry-pick -s -S -x 1c04e1980dfd6debab6e43d9db672c0f01528868

# PR: https://github.com/docker/libnetwork/pull/1991
git cherry-pick -s -S -x 52a9ab55ce92a541798d130a87a84ca34f0b6178
```

### CODE REVIEW

**Comment by eduardolundgren** [comment]
@thaJeztah thank you for backing port this, would be possible to make a release with it?

**Comment by thaJeztah** [comment]
@eduardolundgren this cherry-pick is in preparation of a possible 17.09.1 release; it's still being decided which changes need to be backported and which not.

**Comment by thaJeztah** [comment]
Looks like I may have to cherry-pick https://github.com/docker/libnetwork/pull/1947 into this one to fix the lint-errors

**Comment by eduardolundgren** [comment]
Hopefully, this backport gets into 17.09.1, the current stable release corrupts the managers' quorum when the number of overlay networks gets close to 2000, in addition to that some workers go down randomly.

**Comment by fcrisciani** [comment]
@thaJeztah lint commit is in, can you try to rebase?

**Comment by thaJeztah** [comment]
rebased 👍

**Comment by fcrisciani** [comment]
LGTM

**Comment by eduardolundgren** [comment]
Do you know when `17.09.1` release is gonna happen?
Is this going to also get into `17.10.x` and `17.11.x`?
Sorry for so many questions :)
Thank you again for the fast response.

**Comment by thaJeztah** [comment]
No, I don't have a date for 17.09.1.

17.10 and 17.11 are edge releases, so would only get critical ("P0") patches; with 17.11 being released, docker 17.10 reached EOL.

For your specific issue, the error message indicates it may not be an issue in the networking stack, but due to the raft state becoming too big for syncing between managers; this pull request in SwarmKit raises the maximum size to 128MB; https://github.com/docker/swarmkit/pull/2375, which is being backported to 17.09.1 through https://github.com/docker/docker-ce/pull/323, and should address the direct problem.

A bigger change is being worked on in https://github.com/docker/swarmkit/pull/2458, which will use a streaming mechanism to send raft snapshots.

**Comment by thaJeztah** [comment]
Actually, the size fix was already included in 17.09.0 through https://github.com/docker/docker-ce/pull/242, so I'm not sure if this will address your situation

**Comment by eduardolundgren** [comment]
@thaJeztah raft state becoming too big was only happening when approximately 2000 overlay networks were being created in a 30min time window. In contrary, if 2000 services were being created it was all fine. Supposedly the raft messages for service creation are bigger.

Is there a way to know if `17.09.0-ce-rc3` contains docker/swarmkit#2375?

I just tested on `17.09.0-ce-rc3` from Thu Sep 21 02:32:26 2017 and it seems to be working well. I only had one manager and one worker on this test though, will try again with more managers and see if it's still fine.

**Comment by thaJeztah** [comment]
Yes; the size change was in 17.09.0-ce-rc3; https://github.com/docker/docker-ce/blob/v17.09.0-ce-rc3/components/engine/vendor/github.com/docker/swarmkit/manager/manager.go#L59

Note that rc3 is a release candidate; not the final release (17.09.0-ce was released after that)

**Pull request merged**
