### PR TITLE
Remove dependency on libcontainer

### PR DESCRIPTION
**Pull request by LK4D4**
Also godep save ./... revealed some cleanup

ping @mrjana

### CODE REVIEW

**Comment by mrjana** [comment]
@LK4D4 CI is failing. golint is complaining about the use of ALL_CAPS constants in the code that you imported

**Comment by LK4D4** [comment]
@mrjana fixing

**Comment by LK4D4** [comment]
@mrjana Looks okay now

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
