### PR TITLE
Update libkv in Godep

### PR DESCRIPTION
**Pull request by dave-tucker**
Updates #392

Signed-off-by: Dave Tucker <dt@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks @dave-tucker.
Unfortunately, we don't have integration tests for multi-host networking features.
Can you please perform some manual tests / checks to make sure this godep update doesn't negatively impact the multi-host networking.

**Comment by mavenugo** [comment]
ping @dave-tucker

**Comment by mavenugo** [comment]
#446 updates to the latest. closing this.

**Comment by abronan** [comment]
@mavenugo It's # 466 :wink:

**Comment by mavenugo** [comment]
@abronan oops... updated. as if it never happened :muscle:

**Comment by abronan** [comment]
:muscle: :smile: :+1:

**Pull request closed without merging**
