### PR TITLE
Modified Client to make use of the corrected REST API & service endpoint support

### PR DESCRIPTION
**Pull request by mavenugo**
Also supporting name, id & partial-id lookups for all the network
commands

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
@mrjana Thanks for your comments. Fixed them. PTAL.

**Comment by mrjana** [comment]
LGTM

**Comment by mavenugo** [comment]
Pushed the service UI for docs work... still WIP. will fix the circle-ci failure and push the update soon.

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
