### PR TITLE
Add dummy proxy on port map

### PR DESCRIPTION
**Pull request by LK4D4**
It is needed in cases when mapped port is already bound, or another
application bind mapped port. All this will be undetected because we use
iptables and not net.Listen.

### CODE REVIEW

**Comment by LK4D4** [comment]
docker/docker#13024 for reference

**Comment by LK4D4** [comment]
ping @aboch @mrjana 
We need this in 1.7

**Comment by mrjana** [comment]
@LK4D4 wouldn't this be solved if we start binding to ports when we allocate ports in port allocator? Once issue is the daemon host port is also allocated through the same api but in that we shouldn't bind the port because the daemon will start listening on it. But we can always provide another api like `pa.RequestPortWithoutAlloc` just for daemon case. 

 Right now the portallocator design in such a way that it is in sync with the OS. Which is a problem ...

**Comment by LK4D4** [comment]
@mrjana It would, but now binding logic is in `portmapper`, so I thought it should be there. Also `portallocator` knows nothing about `useProxy` and I don't want to rewrite to release this feature.

**Comment by mrjana** [comment]
@LK4D4 Ideally we don't need a proxy. Just a few more state in portallocator which holds the bind reference. But since this is urgent for 1.7 I am fine with the current design

**Comment by LK4D4** [comment]
@mrjana Yeah, ideally :) But userland-proxy is still defaut :/

**Comment by LK4D4** [comment]
@mrjana I decided to remove mutex at all, because there is no references to proxy until `Start` is called.

**Comment by mrjana** [comment]
@LK4D4 LGTM

**Comment by mavenugo** [comment]
Thanks guys. LGTM.

**Pull request merged**
