### PR TITLE
Fix ipam state cleanup logic

### LINKED ISSUE #659: 1.9.0-rc1 : ipam state cleanup logic does not kick in on network creation failure
Logic got accidentally broken by another fix

Issue was originally reported on irc by @shettyg

### PR DESCRIPTION
**Pull request by aboch**
-  As it got accidentally broken by another commit

Closes #659 
Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch fix LGTM.
Can you write a negative test-case to make sure such issue doenst happen again ?
It would be good to add test cases for both CreateNetwork and CreateEndpoint to make sure we dont hold up pool or ip that is allocated by ipam.

**Comment by mavenugo** [comment]
you can simulate a driver failure by adding a dummy remote driver.

**Comment by aboch** [comment]
@mavenugo Sure I can do that.

**Comment by aboch** [comment]
@mavenugo I added a test to cover the ipam release in case of network and endpoint creation failure.
PTAL

**Comment by mavenugo** [comment]
Thanks @aboch . LGTM.

**Pull request merged**
