### PR TITLE
 Enable Hot Add/Remove of Network Endpoints for Windows

### PR DESCRIPTION
**Pull request by madhanrm**
Use ContainerID as SandBox Id
Signed-off-by: MadhanRaj.Mookkandy@microsoft.com

### CODE REVIEW

**Comment by madhanrm** [comment]
Vendor Commit Pending

**Comment by madhanrm** [comment]
ping @mavenugo @msabansal @dineshgovindasamy

**Comment by madhanrm** [comment]
Looks like HCSShim hasn't been vendor'd in for quite sometime. Is it required to vendor in hcsshim  changes here, if this PR uses an API from the new hcsshim or shall I vendor hcsshim  in docker PR only.

**Comment by JMesser81** [comment]
ping @mavenugo  - we will need this support for hot-add in Windows.

**Comment by madhanrm** [comment]
hcsshim vendor changes from https://github.com/Microsoft/hcsshim/commit/7fb72df30c604381a1bd0e82fa3660d4e3584307

**Comment by madhanrm** [comment]
ping @mavenugo @msabansal @dineshgovindasamy

**Comment by madhanrm** [comment]
Re-Working to integrate with the latest docker

**Comment by madhanrm** [comment]
Updated

**Pull request closed without merging**
