### PR TITLE
netns: Update to latest for arm64

### PR DESCRIPTION
**Pull request by glevand**
Update to the latest netns to get build fixes for arm64.

@hqhq: FYI

### CODE REVIEW

**Comment by mavenugo** [comment]
@glevand can you please also add the `Godeps.json` changes ?
without that the version that we specify in Godeps.json will be different from the content in the _workspace

**Comment by glevand** [comment]
Added Godeps.json changes.

**Comment by mavenugo** [comment]
LGTM,

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
