### PR TITLE
[WIP] Diagnosis framework

### PR DESCRIPTION
**Pull request by fcrisciani**
Introducing a generic framework to enable online debug and remediation.
The framework is compose of 2 components:
1) diagnose server: it allows to open a TCP socket on localhost to which is possible to call remote HTTP handlers registered
2) handlers: modules are allowed to register handlers to expose functionalities for debugging purposes

Example:
NetworkDB registers several handlers to expose the internal data structure and make easier to debug the internal status. Moreover is also able to expose methods to change values of the db itself.

### CODE REVIEW

**Comment by fcrisciani** [comment]
@aboch @mavenugo can you guys give a fist look at the design?
It is still a WIP, I will probably change the handlers, but can you +1/-1 the idea of having a diagnose module where you can simply attach handlers and are automatically exposed?
I think that will be a very flexible tool and make very easy to attach eventually extra components to debug online.

TODO:
clean the code
add the comments
implement the remove handler
add a test and implement a basic client for the network db
create some message structure maybe protobuf

**Comment by sanimej** [comment]
@fcrisciani Its a cool idea to have an in-built diagnostic server. 

From the design point of view we have to consider few things..

1. If the diagnostics server allows internal state to be modified there is a security concern here. One compromised node can easily push states into networkdb that can affect the entire cluster.  At a minimum there has to be TLS with client verification and may be also tied to the authentication of swarm nodes.
2. networkdb currently is a low level distribution mechanism which gets a key and a opaque value. To be of value to the user, the value has to be unmarshaled. That can be done only by the clients of networkdb, ie: overlay driver, libnework core etc. So may be the handler of the diagnostics has to be libnetwork ?
3. The information from networkdb is already presented through the `network inspect verbose` and `Peer` info. Probably the main value of a diagnostics server is the option to modify the state if we can address the previous points.

**Comment by mavenugo** [comment]
@fcrisciani a bit 👍 on the idea. It will be an invaluable operations tool especially for all the black-box states that are out-of-reach for operations team.

@sanimej Regarding your valid security concern, I guess the most important thing that we should be careful about is that this tool should not be able to corrupt a networkdb's gossip neighbor-list for a given network. In other words, using a compromised node a hacker should not be able to get outside of the network scope that that particular network is bound to. If this tool guarantees that, then IMO it is not worse than what we already have. If a hacker has access to a worker node, that hacker has priliminary access to the network db via `docker xxx` commands and can potentially inject data into the scope of that network already. This tool doesnt introduce anything that isnt already not possible. wdyt ?

In that spirit, I would think we should not support "/joinnetwork" & "/leavenetwork".

also cc @trapier who might be interested.

**Comment by fcrisciani** [comment]
Thanks guys for the comments in weekend time, addressing them down.

@sanimej
1) sure that can be done, if I understand correctly to change the config file of the daemon and let it upgrade the config you need sudo access, so for the normal operation to enable the feature or you have root access or the node is compromised. The socket that gets open is localhost so it won't be exposed outside on the network nor be reachable from outside so to access it you need ssh access or console to the physical node.

2) the diagnose module is designed to be generic and should not enter in the matter of the formatting of the data itself same as network db is doing today. All the complexity of the marshalling and unmarshalling of the data structure should resides end to end, for example in the component that writes into the network DB and in the debug client designed to expose visibility on some specific data structure.

3) I believe the scope of this module is for advanced debug sessions, to use in the cases where you need to see all the raw data into the db for example (and eventually with the appropriate security checks modify them). The docker network inspect will always be a more user friendly, data crunched view coming from the state of the node itself. I see them covering non overlapping use cases.
For example with this tool you will be able to see the status of the nodes with any information that they have as such as lamport clocks, failure suspects etc 

@mavenugo 
Sure we can do that, this commit is more to park some of the code that I have right now and get some feedbacks, currently the api was designed for my testing framework, so that with a simple bash script (spawn_cluster.sh) you are able to bring up a fully functional network db cluster and do operations onto it.
It would be also very helpful for me to discuss on Monday the security aspects about a compromised node that participate to a swarm, like what guarantees are still maintained after the breakout.

**Comment by sanimej** [comment]
@fcrisciani Editing the daemon config needs sudo access. But if a node is compromised worst case we have to assume they have root access as well. Or the admin might have already enabled the diagnostics on. So the goal should be to minimize the impact that one node cause. Providing an option to easily update the networkdb which impacts the entire cluster is a security issue.

Even though it is a local socket it has to be secure so that only the authorized person with the certs can use it. Given that, I am not sure if its the right approach to have individual components of docker expose a random port. Think of swarmkit exposing another port for swarm specific diagnostics.

I didn't quite understand your response on unmarshalling. From the user point of view we have to present the actual contents of the db entry, not a protobuf encoded byte stream.

@mavenugo There is also createEntry/updateEntry. Someone who has access to the diag tool can easily update the entries to pull in traffic to a wrong node, intentionally or accidentally.

**Pull request closed without merging**
