### PR TITLE
Do not panic on setns failure

### PR DESCRIPTION
**Pull request by mrjana**
Since panicking on setns failure affects daemon
availability convert them to error log messages.

Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
:+1: Can you please address the minor comment ?

**Comment by mrjana** [comment]
@mavenugo Took care of the comments. PTAL

**Comment by mavenugo** [comment]
Thanks. LGTM.

**Comment by aboch** [comment]
LGTM

**Pull request merged**
