### PR TITLE
Remove unconditional serf debug logging

### PR DESCRIPTION
**Pull request by mrjana**
There were some unconditional debug logging in serf.
Removed them and made then go through logrus writers
based on what error level the log string contains.

Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>

### CODE REVIEW

**Comment by sanimej** [comment]
LGTM

it was useful for quick debugging though :)

**Comment by aboch** [comment]
LGTM

**Comment by mavenugo** [comment]
:pray:

**Comment by mrjana** [comment]
@sanimej All of it is still available if you start your docker or dnet with -D flag :-)

**Pull request merged**
