### PR TITLE
Revert "Merge pull request #2339 from phyber/iptables-check"

### PR DESCRIPTION
**Pull request by arkodg**
This reverts commit 820deef78e53c49f13797a93537325a4b8d53014, reversing
changes made to 19e372a98f736c48e65563db5d7a474fa42d94b4.

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks @arkodg. LGTM

**Comment by arkodg** [comment]
PTAL @euanh @selansen

**Comment by arkodg** [comment]
cc: @thaJeztah

**Comment by thaJeztah** [comment]
This reverts https://github.com/docker/libnetwork/pull/2339

**Pull request merged**
