### PR TITLE
Do not import testing in the main binary.

### PR DESCRIPTION
**Pull request by jfrazelle**
cc @calavera

### CODE REVIEW

**Comment by calavera** [comment]
:metal:

**Comment by mavenugo** [comment]
Thanks @jfrazelle @calavera . Agreed.
Just curious. Do we identify test_*.go as testing related files even if it doesnt follow the *_test.go convention ?

**Comment by calavera** [comment]
@mavenugo we don't import in docker files that start with `test_`, do we?

But I agree that there could be a better way

**Comment by mrjana** [comment]
@jfrazelle We can merge it if we are removing test_* files in `hack/vendor.sh` as well in addition to *_test files. Is this true? Last time I checked test_* files are not getting removed.

**Comment by jfrazelle** [comment]
let me check

**Comment by jfrazelle** [comment]
we don't but let me patch ;)

**Comment by mrjana** [comment]
ok thx :-)

**Comment by mrjana** [comment]
@jfrazelle Instead can we just rename all of `test_*` files to follow `*_test` convention.
That is much better

**Comment by mrjana** [comment]
Which means changing `test_linux.go` to `linux_test.go` and also add `windows_test.go` and `freebsd_test.go`. WDYT?

**Comment by jfrazelle** [comment]
will do

**Comment by jfrazelle** [comment]
done!

**Comment by jfrazelle** [comment]
shit what did I do lol

**Comment by jfrazelle** [comment]
oh build tags my b

**Comment by mrjana** [comment]
@jfrazelle Apologies for sending you in the wrong direction. This function is a test utility that is needed by other packages as well. So changing it to `*_test.go` is not going to work. You may have to change it back to `test_*.go` and add the patch to remove them in `hack/vendor.sh`

**Comment by jfrazelle** [comment]
oh nm

**Comment by mrjana** [comment]
Thanks @jfrazelle LGTM

**Comment by mavenugo** [comment]
so much for convention over configuration :)

LGTM.

**Comment by jfrazelle** [comment]
patching coming to docker ;)

**Comment by jfrazelle** [comment]
here is patch for vendor https://github.com/docker/docker/pull/16024 do u want me to bump libnetwork too?

**Comment by mrjana** [comment]
@jfrazelle Sure.

**Pull request merged**
