### PR TITLE
Issue #184 - Improve Build Image in Makefile

### PR DESCRIPTION
**Pull request by codergr**
Signed-off-by: Sotiris Salloumis <sotiris.salloumis@gmail.com>

### CODE REVIEW

**Comment by codergr** [comment]
Sorry learning the environment I guess commenting on the issue should be enough to see the patch. If not please let me know what actions I need to do.

**Comment by dave-tucker** [comment]
Thanks for the contribution @codergr, LGTM

**Comment by dave-tucker** [comment]
LGTM
/cc @aboch @mrjana @mavenugo

**Comment by aboch** [comment]
@codergr 
When you pushed this PR, code was still quickly evolving. Because of that and other priorities, we did not all allocate time to review your change. Sorry for that.
Given the code has change considerably since then, I will go on and close this one for now.

But please do not esitate to open a new PR, if you see room for improvement in current code.
It will get more attention this time.

**Pull request closed without merging**
