### PR TITLE
[17.09] Serializing bitseq alloc

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry-pick of https://github.com/docker/libnetwork/pull/1788 for 17.09

```
git checkout -b 17.09-backport-ipam_alloc upstream/bump_17.09
git cherry-pick -s -S -x 5790b5c17ce7a6e2733ba0f4dfccced8144237e3
git cherry-pick -s -S -x 0184de8fc5074f94a74a0025ff60dab69cc442a9
git cherry-pick -s -S -x a2bcac00122a43d771af77ff060794dd02bb4a00
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
https://github.com/docker/libnetwork/pull/1947 may be needed to address the lint-errors

**Comment by fcrisciani** [comment]
@abhi can you give the final blessing?

**Comment by abhi** [comment]
corresponding swarmkit change will required as well

**Pull request merged**
