### PR TITLE
Support Go Modules

### PR DESCRIPTION
**Pull request by SamWhited**
Experiment with building modules. If we can get a few of these supporting projects building it will make swapping things out in moby and testing changes much easier than managing vendor trees.

### CODE REVIEW

**Comment by SamWhited** [comment]
This appears to be working. I kept the changes to the Makefile minimal for the sake of having a small change, but there are other simplifications that modules should allow like removing the use of go list and ignoring the vendor tree.

**Comment by thaJeztah** [comment]
could we use go mod in vendoring mode? doing so makes reviewing updates dependencies easier, and we've run in situations in the past where upstream dependencies went AWOL, and were no longer available

**Comment by SamWhited** [comment]
Sure thing; the initial change will still be rather large as Go Modules trims out files it thinks are unnecessary and a few of the versions had to be tweaked to account for revisions that had been removed and the like. I've also added a check that we remembered to update the vendor tree to CI so that it doesn't end up getting out of date.

**Comment by thaJeztah** [comment]
> and a few of the versions had to be tweaked to account for revisions that had been removed and the like

hmm that doesn't sound right; do you have examples? Is this the problem that `go mod` expects commits to be present on _master_ ? (we likely have dependencies  that release from release-branches, and those commits (for most repositories) aren't merged back to master)

**Comment by SamWhited** [comment]
In this case the problem was `github.com/samuel/go-zookeeper` which imports an indirect dependency that no longer exists so modules complain if you try to run `go mod vendor` or `go mod tidy`. In one of the other PRs I was working on it was a commit that no longer existed (I assume a tag or branch was deleted and then GC was run).

**Comment by SamWhited** [comment]
I also found a few (see new replace lines) that were different and go.mod keeps upgrading despite the vendor.conf. I've manually reverted them to the old versions with replace lines for now, they can be removed in future PRs to make this diff smaller.

**Comment by SamWhited** [comment]
Rebased and removed the replace lines because they weren't transitive and were causing problems upstream. This does require updating some deps, so it becomes a bigger change unfortunately.

**Comment by SamWhited** [comment]
Briefly glanced at this bug, I think this will fix it but I didn't want to spend a huge amount of time on it so we'll see what they say: armon/go-radix#12

**Pull request closed without merging**
