### PR TITLE
Cherry-picking a few fixes for 1.9.2

### PR DESCRIPTION
**Pull request by aboch**
Cherry-picking #790 #794 #799 #802

### CODE REVIEW

**Comment by mavenugo** [comment]
@aboch I think we should just pick up #794 #799 #802. The rest of them are not important for the 1.9.2 branch.

**Comment by aboch** [comment]
@mavenugo
Updated the list. I think the race protection one should also go in.

**Comment by mavenugo** [comment]
LGTM.

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
