### PR TITLE
Fixes bug that mistook gw6 for gw.

### PR DESCRIPTION
**Pull request by yyb196**
Fixes bug that mistook gw6 for gw.

Signed-off-by: Frank Yang <yyb196@gmail.com>

### CODE REVIEW

**Comment by andrewhsu** [comment]
cc @tiborvass this may impact live restore for a marshaling event

**Comment by fcrisciani** [comment]
LGTM

**Comment by mavenugo** [comment]
Thanks @yyb196.

 LGTM

**Comment by yyb196** [comment]
this should merge to moby to solve this bug:https://github.com/moby/moby/issues/25981

**Comment by fcrisciani** [comment]
@yyb196 can you open this PR again, we had to revert it because it was showing a new issue in the integration tests in docker. The fix is correct but we will have to debug the test and see what is failing.
Sorry for the trouble

**Comment by yyb196** [comment]
@fcrisciani what should i do to accept https://github.com/docker/libnetwork/pull/1881, and how can i see the error you mentioned in integration test

**Comment by fcrisciani** [comment]
@yyb196 this is the failure:
```
00:28:30.223 FAIL: docker_cli_network_unix_test.go:1677: DockerDaemonSuite.TestDaemonRestartRestoreBridgeNetwork
00:28:30.223 
00:28:30.223 [dd55ca11861f1] waiting for daemon to start
00:28:30.223 [dd55ca11861f1] daemon started
00:28:30.223 
00:28:30.223 [dd55ca11861f1] waiting for daemon to start
00:28:30.223 [dd55ca11861f1] daemon started
00:28:30.223 
00:28:30.223 docker_cli_network_unix_test.go:1733:
00:28:30.223     t.Fatal(err)
00:28:30.223 ... Error: exit status 125
00:28:30.223 
00:28:30.223 [dd55ca11861f1] exiting daemon
```

you should be able to vendor your change on to moby/moby, or simply do the change in the file under the vendor folder.
Then run the test:
`time make TESTFLAGS='-check.f DockerDaemonSuite.TestDaemonRestartRestoreBridgeNetwork' test-integration-cli`

LMK how it goes

**Comment by aboch** [comment]
The same bug is there also in 
`func (epj *endpointJoinInfo) CopyTo(dstEpj *endpointJoinInfo) error {`:

```
dstEpj.gw = types.GetIPCopy(epj.gw6)
```

**Comment by yyb196** [comment]
@aboch you are right! that's why the integration failed

**Comment by yyb196** [comment]
@fcrisciani i have submitted a new pr at https://github.com/docker/libnetwork/pull/1887, could you please review it and see if it is ok to merge?

**Pull request merged**
