### PR TITLE
Fix logrus formatting

### PR DESCRIPTION
**Pull request by daehyeok**
Refactoring logrus import and formatting

Following docker's issue https://github.com/docker/docker/issues/23459

This fix tries to fix logrus formatting by removing `f` from
`logrus.[Error|Warn|Debug|Fatal|Panic|Info]f` when formatting string
is not present.
Also fix import name to use original project name 'logrus' instead of
'log'

### CODE REVIEW

**Comment by daehyeok** [comment]
sorry i confused same PR in swarmkit. i closed previos PR and made it...

**Comment by daehyeok** [comment]
@aboch  i changed commit message
its commit tried to fix import name use "logrus"  instead of mixed usage both of "log" and "logrus"
 and reformating to use w/o 'f' function

**Comment by mrjana** [comment]
@daehyeok Please rebase.

**Comment by daehyeok** [comment]
@mrjana reabsed

**Comment by mrjana** [comment]
@daehyeok There is a genuine CI failure and also needs a rebase again since your PR touches a lot of files :-(

Please fix and rebase once again and we will merge it faster.

**Comment by daehyeok** [comment]
@mrjana  did it again :)

**Comment by mrjana** [comment]
@daehyeok You have a CI failure related to your changes:
```
# github.com/docker/libnetwork
./network_windows.go:54: undefined: log in log.Errorf
godep: go exit status 2
```
Can you fix that?

**Comment by daehyeok** [comment]
@mrjana  i changed that and fix additional files which newly added in Master branch but still use ```log "github.com/Sirupsen/logrus"```

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
