### PR TITLE
API struct tagged to produce proper output when marshalled #217

### PR DESCRIPTION
**Pull request by kunalkushwaha**
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

### CODE REVIEW

**Comment by dave-tucker** [comment]
Thanks @kunalkushwaha this LGTM
/cc @aboch

**Comment by dave-tucker** [comment]
Also @aboch what was the reason that we have duplicate structs in the API and Client packages?
Just to avoid import issues? I wonder if there is an easier way of doing this...
Likely not in scope of this PR, but something that we should track as an issue

**Comment by aboch** [comment]
@dave-tucker this was chosen by @mavenugo when he implemented the client. I think he wanted to provide a client implementation which did not import libnetwork, becasue at the time he implemented it, we did not have the rest api in a separate "api" package ?

**Comment by mrjana** [comment]
LGTM

**Comment by aboch** [comment]
LGTM

**Pull request merged**
