### PR TITLE
ipvlan slaves must inherit the mac-address from parent

### PR DESCRIPTION
**Pull request by mavenugo**
Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
ping @nerdalert

**Comment by mavenugo** [comment]
@sanimej the reason I removed it is because kernel fails with `operation not supported` if we try and set a mac-address for a ipvlan sub-interface. Also in certain kernel versions, even if we set a mac-address, it seems to be ignored. I guess it is safer to not set it up even though the mac-address is empty in inspect.

**Comment by sanimej** [comment]
@mavenugo Its ok to not set the mac. But we should try to show the mac in docker inspect by getting the auto generated mac. If the priority is to fix the basic issue now lets file an issue for the inspect issue and address it later.

**Comment by mavenugo** [comment]
make sense. btw... any changes as you suggested requires driver api changes on the libnetwork core side .. :(

**Comment by sanimej** [comment]
`any changes as you suggested requires driver api changes on the libnetwork core side`

We can create the ipvlan slave interface in the CreateEndpoint and set the mac assigned by the kernel.

**Comment by sanimej** [comment]
LGTM

**Pull request merged**
