### PR TITLE
Show a warning when a subsystem fails to initialize.

### PR DESCRIPTION
**Pull request by calavera**
Users won't know what's going on if we shows a message only in debug mode.

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
Thanks @calavera 
LGTM.

**Comment by mavenugo** [comment]
@calavera come to think of it, the reason it was added under Debug is to make sure we dont throw this warning message in Docker Daemon when not using the experimental channel.
Since the multi-host networking is only part of experimental and the kv-store configuration is required only for multi-host networking, we didnt want to alarm the user for a lack of configuration which is not even required for non-experimental docker.

Having said that, If am not wrong, we will not see this message in the non-experimental version of docker daemon due to the mere fact that none of the cfgs are initialized by default. But, I think that is just a side-effect than by design.

Hence, It will be good to move this message only for experimental version.

**Comment by calavera** [comment]
Now that we've shipped 1.7, this code should not be released again until 1.8, or a experimental version. I think it's fare to assume that these features will land in the final 1.8 release. There is no need to make the log special, it should be a warning every time.

**Comment by mavenugo** [comment]
@calavera from an user standpoint, Warn is a stronger message. my concern with changing the logging level is that we will be unnecessarily warning the user even if the user intention is to NOT use the data-store.

BTW, we will fail with appropriate message anyways if the user tries to create a network or service using `overlay` driver or any other driver that actually has a `GlobalScope` compared to `LocalScope` that default `bridge` driver belongs to.

So, I think having a Warn message for a use-case that the customer really dont want to try seems excessive for me. The only reason we have a Debug message here is for debugging purposes. But I wont mind even removing this message during the init, because we will anyways throw the error message when the user tries to use the kv-store without proper configuration.

WDYT ?

**Pull request closed without merging**
