### PR TITLE
portmapper: touch iptables only for IPv4

### PR DESCRIPTION
**Pull request by stapelberg**
split out of https://github.com/docker/docker/pull/20315
in order to fix https://github.com/docker/docker/issues/11518

Signed-off-by: Michael Stapelberg <stapelberg@google.com>

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by stapelberg** [comment]
Friendly ping?

**Comment by stapelberg** [comment]
Ping?

**Comment by lenovouser** [comment]
Ping

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
