### PR TITLE
Bridge driver to detect and remove stale network 

### PR DESCRIPTION
**Pull request by aboch**
Because of the changes for libnetwork to support live-restore, an issue has been introduced which can be recreated following the steps below.
With the new persist changes in driver for the default bridge network, control has to chnage and Libnetwork directive must be honored so that driver state will reconcile with libnetwork state.

Steps to reproduce:
```
    Step                        docker network ls | grep bridge

0) remove  local kv
1) start   1.11.2:      a44b8e3c87b7        bridge              bridge  
2) stop    1.11.2
3) start   1.12.rc1:    37a965037ed8        bridge              bridge
4) stop    1.12.rc1
5) start   1.11.2:      47986d1209a8        bridge              bridge
6) stop    1.11.2
7) start   1.12.rc1:    FAILS:

FATA[0001] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: cannot create network 3ffb2a2bb6fba983d91a68e0af004890f71964ce43d921263420e8bf6c99599e (docker0): conflicts with network 37a965037ed8a625972f4987e6bbb8797e6af0d58c2eb343ab21a96861b07a7a (docker0): networks have same bridge name 

1.12.rc1 default bridge nw creation will fail the conflict check with a stale default bridge network created at point 3
```

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
I agree. the core manages the correctness and a stale entry (possible if the user downgrades and upgrades the docker daemon) shouldn't cause the delete to fail.
However, i think it is better to go ahead and cleanup any resources associated with such endpoints.

**Comment by icecrime** [comment]
It doesn't seem to solve the problem for me. What I tried:

- Install clean 1.11.2
- Create 3 `busybox top` container, one with default network, one with `--net=host`, one with `--net=none`
- `systemctl stop docker`
- Replace install with 1.12.0-RC1 + this patch
- `systemctl start docker

Daemon doesn't start:

 ```Jun 16 07:36:08 echoes docker[10841]: time="2016-06-16T07:36:08.295208706-07:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: cannot create network 860a13f8b151baa0ddafc652fdae31b3326392e191efdc2ef899a32426060045 (docker0): conflicts with network c18bb5dd68742e4ddbac710053848b4d1c25d92a7c11479a5c6c839e78c33468 (docker0): networks have same bridge name"
```

**Comment by aboch** [comment]
@icecrime
This change is not the one which will fix the issue you hit. The one you are interested in is coming.

**Comment by aboch** [comment]
@mavenugo The stale endpoint is being removed at the next reload by the existing logic in bridge_store.go. Similarly with what is being done in libnetwork core.

**Comment by aboch** [comment]
ping @icecrime @justincormack I completed the diffs. the issue as reported in the description is fixed for me. Please give it a try and let me know how it goes for you.

**Comment by justincormack** [comment]
thanks will test it

**Comment by aboch** [comment]
Did more testing considering the 1.12 --live-restore option after stopping 1.11 with running containers w/o and with `--restart always` policy:

```
The table shows at each step what is the default bridge network ID in Libnetwork store and in bridge driver in memory and  in store.
Between the last two steps, I run 2 containers in -d mode w/o and w/ restart policy set to always.


                  step 1       step 2      step 3    step 4
 cmp    /daem     1.11.2        1.12       1.11        1.12.live-restore
inmem   / ver
instore
 
  LN                A           B          C            D
  BD                A,/         B,B        C,B          D


Repeated the above two times doing:
1) start 2 containers in -d mode at step 3
2) start 2 containers in -d mode with --restart always at step 3

1) works because containers in 1.11 are not restored in 1.12 live-restore
2) works as well, default bridge network states are brought back in sync, 
    no active sandboxes at daemon start. Endpoints are created and Join happens.
 Later, daemon inform libnetwork to disconnect the containers, because of a runtime error not
 related to libnetwork, but that is a different unrelated issue: The containers could join the default 
 bridge network.


ERRO[0001] Failed to start container 55830c423dd22b6d2501657de23c0a109b65b72a6d0d890c4b771eea97b30a50: No such runtime '' 
DEBU[0001] Releasing addresses for endpoint d1's interface on network bridge 
DEBU[0001] ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.3) 
ERRO[0001] Failed to start container 8f3a9ad6e3f79b234d8dc46cf002b60d707bf618d0be825efe950e28697fc852: No such runtime '' 
Full logs:
DEBU[0001] Starting container 55830c423dd22b6d2501657de23c0a109b65b72a6d0d890c4b771eea97b30a50 
DEBU[0001] Starting container 8f3a9ad6e3f79b234d8dc46cf002b60d707bf618d0be825efe950e28697fc852 
DEBU[0001] container mounted via layerStore: /var/lib/docker/aufs/mnt/19f8291ea251fdf91270f725dcf13205dbd662db36e90d697344493a5e40c8af 
DEBU[0001] Assigning addresses for endpoint d0's interface on network bridge 
DEBU[0001] container mounted via layerStore: /var/lib/docker/aufs/mnt/1069ee02b3e15876b3fcfde5cf19ee0870e4383c080490ee0dcf088a7caf034d 
DEBU[0001] RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[]) 
DEBU[0001] Assigning addresses for endpoint d1's interface on network bridge 
DEBU[0001] RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[]) 
DEBU[0001] Assigning addresses for endpoint d0's interface on network bridge 
INFO[0001] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4] 
INFO[0001] IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
DEBU[0001] Programming external connectivity on endpoint d0 (49b72308d0dcc869eb4dcf6ad101b73e703fc2cbdd759c2b855e56f4fb7d4b5e) 
DEBU[0001] Assigning addresses for endpoint d1's interface on network bridge 
INFO[0001] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4] 
INFO[0001] IPv6 enabled; Adding default IPv6 external servers : [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
DEBU[0001] Programming external connectivity on endpoint d1 (c779bccf0770f9486c9ec03f3380d09cb8e7ab22673ddf33c23fca898b0374e4) 
DEBU[0001] Revoking external connectivity on endpoint d0 (49b72308d0dcc869eb4dcf6ad101b73e703fc2cbdd759c2b855e56f4fb7d4b5e) 
DEBU[0001] Revoking external connectivity on endpoint d1 (c779bccf0770f9486c9ec03f3380d09cb8e7ab22673ddf33c23fca898b0374e4) 
DEBU[0001] Releasing addresses for endpoint d0's interface on network bridge 
DEBU[0001] ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.2) 
ERRO[0001] Failed to start container 55830c423dd22b6d2501657de23c0a109b65b72a6d0d890c4b771eea97b30a50: No such runtime '' 
DEBU[0001] Releasing addresses for endpoint d1's interface on network bridge 
DEBU[0001] ReleaseAddress(LocalDefault/172.18.0.0/16, 172.18.0.3) 
ERRO[0001] Failed to start container 8f3a9ad6e3f79b234d8dc46cf002b60d707bf618d0be825efe950e28697fc852: No such runtime '' 
INFO[0001] Daemon has completed initialization          
INFO[0001] Docker daemon                                 commit=e6431de-unsupported graphdriver=aufs version=1.12.0-dev
```

**Comment by mavenugo** [comment]
LGTM.

**Comment by crosbymichael** [comment]
Is there a docker issue that this fixes so that I can reference it when I bump the vendor?

**Comment by aboch** [comment]
@crosbymichael Updated the related ones in the desc

**Comment by seeekr** [comment]
fwiw -- not sure if the issue is supposed to be fixed on 1.11.2, but I experienced it. Had to `rm -rf /var/lib/docker/network` and restart docker daemon in order to get things to a working state again. I can open an issue if this should not have happened.

**Comment by aboch** [comment]
@seeekr 
The fix is present starting in docker 1.12.0

I am not sure you are affected by this issue, because this specific problem was detected when upgrading from 1.11.2 to 1.12 release candidate image (see this PR description).

Your issue may be different, although with similar symptoms.
Please also check the two parent docker/docker issues reported in the description.

If you can reproduce and provide more info feel free to open a new docker/docker issue.

**Comment by seeekr** [comment]
@aboch Thanks for the quick response! I did see at least one of the linked issues and it seemed to have gotten a fixed that was merged around mid June just like this one. And paying closer attention I can see that the issue was reported against 1.12.0-dev... So that means there is probably no fix for 1.11.x coming, potentially this being a different issue?
I can't really provide anything I think that would help narrow down / identify / reproduce the issue (seems to have been one-off), so I'll leave it up to whoever might be interested in tracking down such an issue, though I'm assuming everyone's probably busy enough working on stuff with more tangible issue reports :)
Thanks!

**Pull request merged**
