### PR TITLE
[Backport 17.06] Delete stale HNS endpoints when creating a network

### PR DESCRIPTION
**Pull request by thaJeztah**
Cherry-picks of

- https://github.com/docker/libnetwork/pull/2111 Fix golang.org/x/sync canonical import path
- https://github.com/docker/libnetwork/pull/2098 Delete stale HNS endpoints when creating a network

```
git checkout -b 17.06-fix-stale-hns-endpoints upstream/bump_17.06  
git cherry-pick -s -S -x 756b2d64c978b6006275a9f9075148f94c83cc01
git cherry-pick -s -S -x f2ba9b6a0184454e628f9ea3883bd5220cb7ead2
```

trivial conflict in vendor.conf on the first cherry-pick

When Windows Server 2016 is restarted with the Docker service running, it is
possible for endpoints to be deleted from the libnetwork store without being
deleted from HNS. This does not occur if the Docker service is stopped cleanly
first, or forcibly terminated (since the endpoints still exist in both). This
change works around the issue by removing any stale HNS endpoints for a network
when creating it.

### CODE REVIEW

**Comment by thaJeztah** [comment]
hm failure due to older hcsshim in 17.06;

```
# github.com/docker/libnetwork/drivers/windows
drivers/windows/windows.go:327: undefined: hcsshim.HNSListEndpointRequest
Makefile:53: recipe for target 'cross-local' failed
```

**Comment by thaJeztah** [comment]
Bumped hcsshim to v0.5.17 to match what's used in 17.06. Full diff of that: https://github.com/Microsoft/hcsshim/compare/e439b7d2b63f036d3a50c93a9e0b154a0d50e788...v0.5.17

**Comment by thaJeztah** [comment]
All green now after the bump :+1:

**Comment by mavenugo** [comment]
LGTM

**Comment by mavenugo** [comment]
I will go ahead and merge this 
@johnstep pls add the manual test steps required to validate this change.

**Pull request merged**
