### PR TITLE
Provide API to retrieve Endpoint operational data

### PR DESCRIPTION
**Pull request by aboch**
- from the driver

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by tomdee** [comment]
What data will be returned by EndpointData? Should this PR also update the design doc with this information?

**Comment by aboch** [comment]
@tomdee This API is being added for retrieving endpoint's operational data which is known by and stored by the network driver only. For now this data consists of the container to host port bindings only, but the return format is generic enough (map[string]interface{}) to carry any other operational data.

The port mapping data is needed by docker  "port" and "ps" sommands among others to print the active host port mappings.

Good point, let me add a usage example in README.md

**Comment by mrjana** [comment]
LGTM

**Comment by squaremo** [comment]
> The port mapping data is needed by docker "port" and "ps" sommands among others to print the active host port mappings.

Does that mean a driver is required to return port mappings?

**Comment by aboch** [comment]
@squaremo, if the driver does not support the port mapping programming, then it has to return error during the docker call to Network.EndpointCreate().

**Pull request merged**
