### PR TITLE
Some users docs with a Vagrant setup

### PR DESCRIPTION
**Pull request by runseb**
Just a bit of documentation which I think can help other folks trying to get a feel for things.
Contains a Vagrantfile that I stuck in the same directory, might be better somewhere.

### CODE REVIEW

**Comment by mavenugo** [comment]
@runseb thanks a lot for this. very useful. will review it more closely.

**Comment by runseb** [comment]
made a few tweaks based on @botchagalupe comments. 

1- default mulithost network did not appear if there was no containers started yet.
2- symlink of netns to /var/run/docker/netns to list the interfaces
3- ip -d link show in the last commands to see the vxlan interface and links.

squashed too quickly probably.

**Comment by mrjana** [comment]
@runseb This will be a great addition to libnetwork project. LGTM

**Comment by botchagalupe** [comment]
I reviewed the doc and it all works as described in the markdown.

**Comment by mavenugo** [comment]
Thanks @runseb LGTM.

**Pull request merged**
