### PR TITLE
Avoid persisting ipam data if it can be reconstructed

### PR DESCRIPTION
**Pull request by aboch**
Related: https://github.com/docker/docker/issues/23078

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by sanimej** [comment]
LGTM

**Comment by sanimej** [comment]
@aboch Thanks for adding the capability for the remote drivers

**Comment by mavenugo** [comment]
LGTM

**Comment by chenchun** [comment]
I think such of the non-atomic problems should be solved if we can make use of atomic operations? I know that all storage backend zookeeper/consol/etcd/boltdb support atomic put/delete of multiple KVs. Perhaps libkv should support atomic put/delete of multiple KVs.

**Pull request merged**
