### PR TITLE
Update netlink library.

### PR DESCRIPTION
**Pull request by xnox**
Signed-off-by: Dimitri John Ledkov <dimitri.j.ledkov@intel.com>

### CODE REVIEW

**Comment by xnox** [comment]
Looks like circleci is a bit borked at the moment...
````
Checkout using deploy key: bd:61:39:0a:07:66:6d:2b:75:a8:d0:14:e1:98:93:cb00:02config
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists. git command i returned 128:
````

**Comment by aboch** [comment]
@xnox 
Can you please add to the PR description which improvement/bug fix this update brings in.
Thanks.

**Comment by thaJeztah** [comment]
ping @xnox can you update the PR description (and the commit message)?

**Comment by mrjana** [comment]
LGTM

**Comment by aboch** [comment]
LGTM

**Pull request merged**
