### PR TITLE
add s390x arch build info at the netlink_deprecated_linux bridge driver

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Comment by aboch** [comment]
@jordimassaguerpla Do you still want this change in ? If so, please take care of the formatting issues (see below) and sign your commit. Thanks.

```
Checking format... 
test -z "$(gofmt -s -l . | grep -v Godeps/_workspace/src/ | tee /dev/stderr)"
drivers/bridge/netlink_deprecated_linux_s390x.go
Makefile:55: recipe for target 'check-format' failed
```

**Comment by jordimassaguerpla** [comment]
@aboch : Hi! Sorry I totally forgot about this PR. Yes, I am still interested on having this accepted.
I fixed the formatting issue and signed the commit.
Tests are green now but it complains about not having signed the commit ??? Well I did... did I did it wrong? or is there anything else I can do?

thanks

**Comment by jordimassaguerpla** [comment]
@aboch : Hi! Tests are green and checks have passed. Is there anything else that I should do ?

**Comment by mrjana** [comment]
@jordimassaguerpla I think we are good. LGTM

**Comment by aboch** [comment]
LGTM

**Pull request merged**
