### PR TITLE
Add support for FreeBSD in portallocator

### PR DESCRIPTION
**Pull request by tomoyat1**
Hello,

I am working on getting a modern version of docker to work on FreeBSD as a docker host.
These are the first changes I have made.

### CODE REVIEW

**Comment by tomoyat1** [comment]
Woops, I should have checked the CONTRIBUTING document. My bad.

**Comment by vieux** [comment]
@kvasdopil could you help us review this one ?

**Comment by kvasdopil** [comment]
lgtm

**Comment by kvasdopil** [comment]
Also, afaik, majority of code for solaris platform should be freebsd-compatible so for prototype you can use that. Not sure that applies to network stuff though.

**Comment by fcrisciani** [comment]
LGTM

**Pull request merged**
