### PR TITLE
Shorten controller ID in exec-root to not hit UNIX_PATH_MAX

### PR DESCRIPTION
**Pull request by Rid**
Signed-off-by: Grant Millar <rid@cylo.io>

Use short controller ID in setkey in order to avoid https://github.com/moby/moby/issues/39608 where using a custom exec-root which contains > 27 chars before the controller ID causes the daemon to fail starting with:

```
failed to start daemon: Error initializing network controller: error obtaining controller instance: listen unix /cylostore/sdj/9598/var/run/docker/libnetwork/b2757cb82eadaaea94aab22529663e38c3bf799369f5b578fe8a5bb4bcefe0f0.sock: bind: invalid argument
```

This happens due to hitting the UNIX_PATH_MAX limit (which is 108, ours is 115 in the example above). The patch gives us 79 chars to play with vs 27.

### CODE REVIEW

**Comment by Rid** [comment]
@fcrisciani @ctelfer @AkihiroSuda PTAL?

**Comment by arkodg** [comment]
@Rid can you please retry, the failed test is `flaky` and will be fixed soon

**Comment by Rid** [comment]
@arkodg done, it's now passed.

**Comment by arkodg** [comment]
thanks @Rid 
cc @euanh @selansen

**Comment by selansen** [comment]
Thanks @Rid

**Pull request merged**
