### PR TITLE
networkdb: fix race in deleteNetwork

### PR DESCRIPTION
**Pull request by LK4D4**
There are multiple places which read from that slice(i.e. bulkSync).

### CODE REVIEW

**Comment by aboch** [comment]
CI failure is legitimate:

```
# github.com/docker/libnetwork/networkdb
networkdb/networkdb.go:501: invalid operation: name == nodeName (mismatched types int and string)
networkdb/networkdb.go:504: cannot use name (type int) as type string in append
```

**Comment by LK4D4** [comment]
@aboch fixed! Sorry for that.

**Comment by aboch** [comment]
I see that `func (nDB *NetworkDB) deleteNetworkNode()` is always called under `nDB` lock. The same is true for the counterpart function `func (nDB *NetworkDB) addNetworkNode()`.
Which makes me think this is why no precaution is taken inside these functions while manipulating the map content.

How would a race be possible, can you point me to the code path. Thanks.

**Comment by LK4D4** [comment]
@aboch Sure, nodes slice is not protected by anything, so it can be modified in `deleteNetworkNode` and read in https://github.com/docker/libnetwork/blob/master/networkdb/cluster.go#L416 for example. And it's not a single usage of that slice as I see.
I think that `addNetworkNode` is probably racy too, but it's not so obvious.

**Comment by aboch** [comment]
Oh I see, the code allows to get the nodes slice and manipulate it outside of these two functions.
Thanks for the pointer.

LGTM

**Comment by sanimej** [comment]
LGTM

**Pull request merged**
