### PR TITLE
marshal/unmarshal for overlay multiple subnets

### LINKED ISSUE #592: Overlay - fix datastore marshal/unmarshal for multiple subnets

### PR DESCRIPTION
**Pull request by sanimej**
Fixes #592

Signed-off-by: Santhosh Manohar <santhosh@docker.com>

### CODE REVIEW

**Comment by mrjana** [comment]
@sanimej One general question on the PR. If a node (where the network was not created) joins the network it will get the network from store. But if a vxlan id got allocated subsequently by another node and it updates the network object in store how does the other node get this information. We don't watch on any network store change. so the other nodes will never get that update

**Comment by sanimej** [comment]
@mrjana When one node allocates the vxlan id for a subnet and the container joins the network other nodes will eventually get the serf join update. When processing that we will check the subnet and try to retrieve the vxlan id for that subnet from the store. If this is the first peer update for a subnet it will trigger the setting up of the required plumbing..

**Comment by mrjana** [comment]
@sanimej got it.  One more thing. You still need to install the route for all the subnets in all the containers. Right?

**Comment by sanimej** [comment]
@mrjana yes. Looks like we need a per sub-net route, all pointing to interface on the overlay network. Otherwise because of the default gateway service inter-subnet packets will end up going to the bridge network. I am looking into this issue..

**Comment by mavenugo** [comment]
@sanimej yes. I thought that is the design. the `default-gateway` will handle the default route, while individual routes are managed by the driver directly.

**Comment by sanimej** [comment]
@mrjana @mavenugo pushed the change to add the static route for all the subnets when the container first joins one of the subnets in the network. PTAL

**Comment by mavenugo** [comment]
LGTM.

Lets add proper IT once the dnet UX is enhanced to accept (multiple) subnets.

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
