### PR TITLE
Relax route overlap check, skip for gateway redirect routes

### LINKED ISSUE #779: Unable to create docker0 if VPN is active
```
~ > ip route
0.0.0.0/1 via 10.8.0.5 dev tun0 
default via 192.168.1.1 dev wlp3s0  proto dhcp  src 192.168.1.191  metric 10 
default via 192.168.1.1 dev enp2s0  proto dhcp  src 192.168.1.181  metric 20 
10.8.0.1 via 10.8.0.5 dev tun0 
10.8.0.5 dev tun0  proto kernel  scope link  src 10.8.0.6 
23.196.166.175 via 192.168.1.1 dev wlp3s0 
128.0.0.0/1 via 10.8.0.5 dev tun0 
192.168.1.0/24 dev enp2s0  proto kernel  scope link  src 192.168.1.181 
192.168.1.0/24 dev wlp3s0  proto kernel  scope link  src 192.168.1.191 
192.168.1.1 dev wlp3s0  proto dhcp  scope link  src 192.168.1.191  metric 10 
192.168.1.1 dev enp2s0  proto dhcp  scope link  src 192.168.1.181  metric 20 
~ > sudo docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.          
INFO[0000] API listen on /var/run/docker.sock           
INFO[0000] [graphdriver] using prior storage driver "btrfs" 
INFO[0000] Firewalld running: false                     
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: failed to parse pool request for address space "LocalDefault" pool "" subpool "": could not find an available predefined network 
```

If I stop my VPN, then I'm able to create the interface.

```
~ > sudo systemctl stop openvpn@primary.service
~ > ip route
default via 192.168.1.1 dev wlp3s0  proto dhcp  src 192.168.1.191  metric 10 
default via 192.168.1.1 dev enp2s0  proto dhcp  src 192.168.1.181  metric 20 
23.196.166.175 via 192.168.1.1 dev wlp3s0 
192.168.1.0/24 dev enp2s0  proto kernel  scope link  src 192.168.1.181 
192.168.1.0/24 dev wlp3s0  proto kernel  scope link  src 192.168.1.191 
192.168.1.1 dev wlp3s0  proto dhcp  scope link  src 192.168.1.191  metric 10 
192.168.1.1 dev enp2s0  proto dhcp  scope link  src 192.168.1.181  metric 20 
~ > sudo docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.          
INFO[0000] API listen on /var/run/docker.sock           
INFO[0000] [graphdriver] using prior storage driver "btrfs" 
INFO[0000] Firewalld running: false                     
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=a34a1d5-dirty execdriver=native-0.2 graphdriver=btrfs version=1.9.1
^CINFO[0003] Processing signal 'interrupt'  
```

After the interface is created, then there's no issues with starting the daemon while my VPN is active.

```
~ > sudo systemctl start openvpn@primary.service
~ > ip route
0.0.0.0/1 via 10.8.0.5 dev tun0 
default via 192.168.1.1 dev wlp3s0  proto dhcp  src 192.168.1.191  metric 10 
default via 192.168.1.1 dev enp2s0  proto dhcp  src 192.168.1.181  metric 20 
10.8.0.1 via 10.8.0.5 dev tun0 
10.8.0.5 dev tun0  proto kernel  scope link  src 10.8.0.6 
23.196.166.175 via 192.168.1.1 dev wlp3s0 
128.0.0.0/1 via 10.8.0.5 dev tun0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.1.0/24 dev enp2s0  proto kernel  scope link  src 192.168.1.181 
192.168.1.0/24 dev wlp3s0  proto kernel  scope link  src 192.168.1.191 
192.168.1.1 dev wlp3s0  proto dhcp  scope link  src 192.168.1.191  metric 10 
192.168.1.1 dev enp2s0  proto dhcp  scope link  src 192.168.1.181  metric 20 
~ > sudo docker -d
Warning: '-d' is deprecated, it will be removed soon. See usage.
WARN[0000] please use 'docker daemon' instead.          
INFO[0000] API listen on /var/run/docker.sock           
INFO[0000] [graphdriver] using prior storage driver "btrfs" 
INFO[0000] Firewalld running: false                     
INFO[0000] Default bridge (docker0) is assigned with an IP address 172.17.0.1/16. Daemon option --bip can be used to set a preferred IP address 
INFO[0000] Loading containers: start.                   

INFO[0000] Loading containers: done.                    
INFO[0000] Daemon has completed initialization          
INFO[0000] Docker daemon                                 commit=a34a1d5-dirty execdriver=native-0.2 graphdriver=btrfs
```

### PR DESCRIPTION
**Pull request by aboch**
Fixes #779 

This was suggested by @slayer in https://github.com/docker/docker/issues/24738#issuecomment-267735948

It seems reasonable to skip these special routes when validating a predefined address pool for the `bridge` network or for any user-defined network. At the end we already do it for the default route.

This would ease the docker installation process and docker network create for systems which are running a VPN agent.

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by sanimej** [comment]
@aboch Root cause of this issue is checking the conflict with the entries in the routing table. I am not sure why its done this way. Since we assign subnets in the private IP range and rely on NAT for reaching the service from outside we only have to check the subnets of the hosts interfaces.

In fact, the only reason this problem doesn't happen for the default route is because netlink library returns it as `Dst: <nil> Src: <nil> Gw: 10.0.2.2`. And the reason OpenVPN is installing 0.0.0.0/1 instead of a default route is just a hack/convenience so that users doesn't remove the existing default route.

Unless there is a specific reason we are checking against the routing table I think the fix should be to use the interface subnets for the conflict check.

**Comment by aboch** [comment]
@sanimej 
Yes, that check has always been that way since libnetwork was created.
It already catches the local interfaces, them being directly connected routes.

If your host is connected to a VPN for example, you cannot exclude there is a 172.18.x.x route on the same virtual network.

We cannot assume the default address pools will only be private ranges as we will shortly allow users to configure them.

NAT is not guaranteed to be there for all local scope network, think of MACVLAN driver network.

**Comment by sanimej** [comment]
`NAT is not guaranteed to be there for all local scope network, think of MACVLAN driver network.` 

purpose of macvlan is to plumb to the underlay. So in any deployment of macvlan user has to configure the subnet explicitly.

`If your host is connected to a VPN for example, you cannot exclude there is a 172.18.x.x route on the same virtual network.`

Its not any different from a default route because you don't know what subnets are reachable through the default route. If any deployment where the private IPs are routable across hosts user has to configure the subnet explicitly. And in cases where private subnets are local to the host (most of the users running into this issue) its sufficient to check only the interfaces on that host.

**Comment by aboch** [comment]
@sanimej
I see your point, but I am not comfortable in modifying this logic now, after it has been in place for 6+ releases.

Looking again at this PR itself, I agree it is a kind of an hack to embed in the route overlap check a skip for the vpn redirect routes.

Therefore, I'd prefer to close this PR, and leave the current logic unaltered.

**Pull request closed without merging**
