### PR TITLE
[19.03] revert controller: Check if IPTables is enabled for arrangeUserFilterRule ENGCORE-1114

### PR DESCRIPTION
**Pull request by thaJeztah**
reverts https://github.com/docker/libnetwork/pull/2339

[ENGCORE-1114]

[ENGCORE-1114]: https://docker.atlassian.net/browse/ENGCORE-1114

### CODE REVIEW

**Comment by arkodg** [comment]
PTAL @selansen @mavenugo

**Comment by kolyshkin** [comment]
unit-tests CI fails:
```
read tcp 172.27.0.3:34670->104.196.25.67:2376: read: connection timed out
make: *** [Makefile:123: unit-tests] Error 1
Exited with code 2
```
not sure where it's coming from

**Comment by selansen** [comment]
Re running CI

**Comment by thaJeztah** [comment]
> This is not a backport of #2466 to 19.03 branch, but it's identical, right? I look at the changes and they seem to be the same.

@kolyshkin ah, yes, you're right; also see https://github.com/docker/libnetwork/pull/2467. Perhaps you have thought on that

**Comment by selansen** [comment]
@kolyshkin , All green now

**Pull request merged**
