### PR TITLE
Clean unused variables

### PR DESCRIPTION
**Pull request by WeiZhang555**
Clean some unused variables and format code.

also fix typo: change `RegisterOpamDriver()` into `RegisterIpamDriver()`

Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
ping @mavenugo @aboch 
What do you think of this?

**Comment by mavenugo** [comment]
LGTM. 
We will merge this in master, once we pull the 0.5 branch shortly.

**Comment by WeiZhang555** [comment]
@mavenugo OK, thank you! Really glad to see `libnetwork` grows better and better! :smile:

**Comment by WeiZhang555** [comment]
I see the typo `RegisterOpamDriver() => RegisterIpamDriver()` has been fixed in another PR, now there's only some cleanup work and format problem here.
So I wonder whether this is also ready to be merged? :smile: 
ping @mrjana @aboch

**Comment by aboch** [comment]
LGTM

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
