### PR TITLE
Fix IPAM driver documentation

### PR DESCRIPTION
**Pull request by aboch**
- ipam.md should only describe the contract
  which is relevant to remote ipam plugins.

Addresses https://github.com/docker/libnetwork/pull/908#issuecomment-185807096

Signed-off-by: Alessandro Boch <aboch@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
LGTM

**Comment by mavenugo** [comment]
@aboch can you pls add a pointer fo `go-plugins-helper` project and point to that as the API that plugins must make use of ?

**Comment by aboch** [comment]
@mavenugo Added the reference. PTAL.

**Comment by mavenugo** [comment]
LGTM

**Pull request merged**
