### PR TITLE
Add nice image illustrating CNM

### PR DESCRIPTION
**Pull request by zachgersh**
Figured it would be nice to include the visual aid for anyone who wants to refer back it.

### CODE REVIEW

**Comment by thaJeztah** [comment]
If we do this, I think the image itself should be added to the repository as well, so that the docs don't rely on an external website.

**Comment by zachgersh** [comment]
Agreed! I will update the request tonight.

**Comment by mavenugo** [comment]
Thanks. LGTM.

**Comment by zachgersh** [comment]
Thanks @mavenugo  - I was wondering if the docs are actually being kept up to date?  We noticed some of the interfaces have changed without the docs being corrected.  I could make the changes I think belong in a separate request.

**Comment by mavenugo** [comment]
@zachgersh thanks. pls submit PRs to fix any docs inconsistencies.

**Comment by mrjana** [comment]
LGTM

**Pull request merged**
