### PR TITLE
Enable Linux bridge ProxyArpWifi

### PR DESCRIPTION
**Pull request by djlwilder**
This change enables the Linux bridge's ProxyArpWiFi feature eliminating
the need to flood ARP packets. When an endpoint is created the bridge
driver already has the data needed to complete arp and fdb table
entries. Rather than let the kernel discover this information on its own
we populate the arp and fdb tables when the endpoint is configured.  All
other broadcast traffic will pass normal allowing the administrator to
manage it using ebtables.

Linux bridge ProxyArpWifi is enabled with:
--opt com.docker.network.bridge.proxyarp=1

Dependencies:
linux kernel v4.1-rc1 or later(commit 842a9ae08a25671db3d4f689eed68b4d64be15b5)
vishvananda/netlink commit b144143ea1df18e21a08e2ec101ada9a94a9cc85

Signed-off-by: David Wilder <wilder@us.ibm.com>

### CODE REVIEW

**Comment by djlwilder** [comment]
Some background on this change:
One obstacle to scaling a bridge network is the management of broadcast packets. To emulate a Ethernet type network the Linux bridge must deliver broadcast packets to every port of the bridge. This is accomplished by cloning and flooding broadcasts to every endpoint.  Each of these cloned packets becomes an ingress packet in the kernel's network stack. If a bridge has 1024 ports one broadcast packets must be process by the kernel 1024 times. We have demonstrated running 10,000 containers on a single bridge network increasing the issue ten fold. Using multiple smaller L3 networks can reduce this overhead but creates additional management problems.

The ARP protocol makes use of broadcast packets when sending who-has requests. In our 10,000 node tests, we will send Arp who-has packets to all 10,000 nodes, this requires the kernel to process 100,000,000 broadcast packets (all but 10k are dropped)!  This can cause the kernel's network ingress queues to overflow resulting in packet drops and connection establishment timeouts. I  have seen this problem with configurations of only a few thousand nodes as well, even when using multiple bridges.  Increasing the size of the ingress queue helps but results in higher latency when the queue is filled with broadcast packets. Brtables can be used to eliminate broadcast traffic or to limit delivery to a small number of endpoints.  However, doing so breaks the Arp protocol as arps relies on broadcast packets. This change enables the Linux bridge's ProxyArpWiFi feature eliminating the need flood ARP packets. All other broadcast traffic will pass normal allowing the administrator to manage it using ebtables.

**Comment by djlwilder** [comment]
Question:
This change depends on a recent commit to vishvananda/netlink.  Should I post an update to vendor.conf to reflect this dependency?

**Comment by aboch** [comment]
Thanks @djlwilder . Yes, please include a second commit in your PR in which you update to the netlink vendoring.

**Comment by djlwilder** [comment]
Thanks @aboch, I updated  vendor.conf.  However cI is still failing due to vendoring.  Do I need to do something to fix this?

**Comment by aboch** [comment]
@djlwilder Modifying the vendor.conf file is only step one, second you need to run the `vndr` binary to import the new vendored files (instruction [here](https://github.com/LK4D4/vndr/blob/master/README.md)).

Once done, don't forget to add `vendor.conf` and the new modified/imported files to a specific vendor commit, apart from the commit with the bridge files changes.

**Comment by djlwilder** [comment]
My apologies,  I messed up this pull request.  I am closing it and will try again with a new request. Thanks

**Pull request closed without merging**
