### PR TITLE
Ensure Keys are watchable with etcd

### PR DESCRIPTION
**Pull request by abronan**
etcd v2.0+ with API v2 cannot watch on a regular key, we must enforce
the 'IsDir' parameter while creating the key for it to be considered
as a directory.

This step is necessary unless 'libkv' includes and supports the new
etcd API v3 which removes the directory/key distinction to allow for
a better abstraction.

Fixes: #392
See: docker/libkv#20

Signed-off-by: Alexandre Beslic <abronan@docker.com>

### CODE REVIEW

**Comment by abronan** [comment]
depends on docker/libkv#75

**Comment by tomdee** [comment]
@mavenugo What needs to happen for this to get merged? The libkv changes have been merged so do you just need to tell circleCI to run the tests again?

**Comment by mavenugo** [comment]
@tomdee this PR must update libkv Godeps vendor in. thats it :)
@abronan can you please take care of that ?

**Comment by mrjana** [comment]
@abronan We don't do any `WatchTree` in libnetwork any more. Do we still need this?

**Comment by mavenugo** [comment]
@mrjana good point... forgot about it :)

**Comment by abronan** [comment]
@tomdee @mavenugo @mrjana Yes this PR is useless now with the latest changes ;)

Will test again though to make sure it works with `etcd`.

Closing.

**Comment by mavenugo** [comment]
@abronan btw, do we need to upgrade the libkv version in libnetwork in order to use the latest etcd client ? Will that get us anything that is not already available in the current version ?

**Comment by abronan** [comment]
@mavenugo It will get you nothing if you don't use `WatchTree` ;) maybe faster on the first Put because it involves less round-trip with the `etcd` server. Aside from general performance with the client (and I can't backup this claim yet), IDK. We should still update `libkv` here as we don't know if `go-etcd` is going to work well with the new `etcd` versions in the future. Having this one ensures that the client is actually supported.

**Pull request closed without merging**
