### PR TITLE
Remove stale ip pool on daemon starting

### LINKED ISSUE #1188: daemon ungraceful shutdown during starting make daemon failed to start next time with Error initializing network controller
see https://github.com/docker/docker/issues/22834

### PR DESCRIPTION
**Pull request by coolljt0725**
Fixes #1188 
ping @aboch 

Signed-off-by: Lei Jitang <leijitang@huawei.com>

### CODE REVIEW

**Comment by coolljt0725** [comment]
@aboch what do you think about this?

**Comment by coolljt0725** [comment]
ping @aboch

**Comment by aboch** [comment]
https://github.com/docker/libnetwork/issues/1188#issuecomment-234357183

**Comment by coolljt0725** [comment]
Confirm it is fixed on master

**Pull request closed without merging**
