### PR TITLE
libnetwork cherry-picks for 17.06.0 rc3

### PR DESCRIPTION
**Pull request by andrewhsu**
Cherry-picks taken from:
* https://github.com/docker/libnetwork/pull/1786 Fix leak of watchMiss goroutine
* https://github.com/docker/libnetwork/pull/1787 Fix leak of handleTableEvents
* https://github.com/docker/libnetwork/pull/1789 Set kernel specific config on linux
* https://github.com/docker/libnetwork/pull/1795 Fix OS tweaks call
* https://github.com/docker/libnetwork/pull/1792 Remove dynamic mac entry from fdb on endpoint deletion

### CODE REVIEW

**Comment by andrewhsu** [comment]
cc @mavenugo @tiborvass

**Comment by fcrisciani** [comment]
#1789 needs also https://github.com/docker/libnetwork/pull/1795 to work properly

**Comment by andrewhsu** [comment]
@fcrisciani updated

**Comment by fcrisciani** [comment]
LGTM
Thanks @andrewhsu

**Comment by sanimej** [comment]
@andrewhsu For 17.06.rc3 we need https://github.com/docker/libnetwork/commit/ae6824ea646a89853afa145a90f56e449f4d3a4f as well.

**Comment by andrewhsu** [comment]
@sanimej it is in

**Comment by mavenugo** [comment]
Thanks @andrewhsu @tiborvass LGTM.

**Pull request merged**
