### PR TITLE
Dockerfile: update to Golang 1.12.17

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by arkodg** [comment]
ptal @selansen

**Comment by selansen** [comment]
shouldn't we bump up to 1.13.8 ?

**Comment by thaJeztah** [comment]
@selansen I have https://github.com/docker/libnetwork/pull/2514 for that; first bumping to latest 1.12 version (which is what 19.03 is using right now); I'll backport that one to the 19.03 release branch, then I'll prepare bumps to 1.13 for an upcoming patch release.

Basically these versions are only used in CI, but it's good to have them match what's used in moby / docker, in case there's tests that have issues on newer go versions

**Comment by selansen** [comment]
> @selansen I have #2514 for that; first bumping to latest 1.12 version (which is what 19.03 is using right now); I'll backport this one to the 19.03 release branch, then I'll prepare bumps to 1.13 for an upcoming patch release.
> 
> Basically these versions are only used in CI, but it's good to have them match what's used in moby / docker, in case there's tests that have issues on newer go versions

Got it. Thanks

**Pull request merged**
