### PR TITLE
Fixed getNetworkFromStore, which returned an incorrect struct

### PR DESCRIPTION
**Pull request by espensuenson**
Fixed getNetworkFromStore, which returned incorrect network information - notably, the 'resolver' field was empty.

This fixes https://github.com/moby/moby/issues/38901

Signed-off-by: Espen Suenson <mail@espensuenson.dk>

### CODE REVIEW

**Comment by espensuenson** [comment]
@thaJeztah any chance that this PR will be looked at soon? We cannot use docker networks for continuous integration until the associated bug is fixed.

**Comment by thaJeztah** [comment]
ping @euanh @vikramhh @arkodg PTAL

**Comment by espensuenson** [comment]
@vikramhh I changed it to return immediately in case of error.

**Comment by vikramhh** [comment]
@espensuenson - thanks.  LGTM

**Pull request merged**
