### PR TITLE
Fix map access race in populatedEndpoints

### PR DESCRIPTION
**Pull request by mrjana**
Signed-off-by: Jana Radhakrishnan <mrjana@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
LGTM

**Comment by sanimej** [comment]
LGTM

**Comment by cmingxu** [comment]
I am thinking is a RWLock more suitable for this scenario ?

**Comment by cmingxu** [comment]
https://github.com/docker/libnetwork/pull/1506

**Pull request merged**
